export interface ContentSuggestion {
  id: string;
  category: 'lover' | 'new_start' | 'achievement' | 'wedding' | 'respect' | 'family' | 'general';
  lang: 'ko' | 'en';
  content: string;
  author?: string; // For Quotes
}

export const CATEGORY_LABELS: Record<string, string> = {
  lover: '연인 (Lover)',
  new_start: '새로운 출발 (New Start)',
  achievement: '성공/이직 (Achievement)',
  wedding: '결혼/기념일 (Wedding)',
  respect: '존경/감사 (Respect)',
  family: '부모님 (Family)',
  general: '일반 (General)'
};

/**
 * Famous Quotes for the Left Page
 */
export const QUOTE_SUGGESTIONS: ContentSuggestion[] = [
  // Lover
  { id: 'q-lov-1', category: 'lover', lang: 'ko', author: '윌리엄 셰익스피어', content: '사랑은 눈으로 보지 않고 마음으로 본다.' },
  { id: 'q-lov-1e', category: 'lover', lang: 'en', author: 'William Shakespeare', content: 'Love looks not with the eyes, but with the mind.' },
  { id: 'q-lov-2', category: 'lover', lang: 'ko', author: '빅토르 위고', content: '인생의 가장 큰 행복은 사랑받고 있다는 확신이다.' },
  { id: 'q-lov-2e', category: 'lover', lang: 'en', author: 'Victor Hugo', content: 'The greatest happiness of life is the conviction that we are loved.' },
  { id: 'q-lov-3', category: 'lover', lang: 'ko', author: '앙투안 드 생텍쥐페리', content: '사랑은 서로 마주 보는 것이 아니라, 같은 방향을 함께 바라보는 것이다.' },
  { id: 'q-lov-3e', category: 'lover', lang: 'en', author: 'Antoine de Saint-Exupéry', content: 'Love does not consist in gazing at each other, but in looking together in the same direction.' },
  { id: 'q-lov-4', category: 'lover', lang: 'ko', author: '로버트 브라우닝', content: '나와 함께 늙어가자! 가장 좋은 날은 아직 오지 않았다.' },
  { id: 'q-lov-4e', category: 'lover', lang: 'en', author: 'Robert Browning', content: 'Grow old along with me! The best is yet to be.' },
  { id: 'q-lov-5', category: 'lover', lang: 'ko', author: '마틴 루터 킹', content: '사랑은 유일하게 원수를 친구로 바꿀 수 있는 힘이다.' },
  { id: 'q-lov-5e', category: 'lover', lang: 'en', author: 'Martin Luther King Jr.', content: 'Love is the only force capable of transforming an enemy into a friend.' },
  { id: 'q-lov-6', category: 'lover', lang: 'ko', author: '헤르만 헤세', content: '내가 사랑이 무엇인지 안다면, 그것은 당신 덕분입니다.' },
  { id: 'q-lov-6e', category: 'lover', lang: 'en', author: 'Hermann Hesse', content: 'If I know what love is, it is because of you.' },
  { id: 'q-lov-7', category: 'lover', lang: 'ko', author: '단테 알리기에리', content: '사랑은 태양과 다른 별들을 움직인다.' },
  { id: 'q-lov-7e', category: 'lover', lang: 'en', author: 'Dante Alighieri', content: 'Love moves the sun and the other stars.' },
  { id: 'q-lov-8', category: 'lover', lang: 'ko', author: '라이너 마리아 릴케', content: '사랑은 두 고독이 서로 보호하고, 경계하고, 인사하는 것이다.' },
  { id: 'q-lov-8e', category: 'lover', lang: 'en', author: 'Rainer Maria Rilke', content: 'Love consists in this, that two solitudes protect and border and salute each other.' },
  { id: 'q-lov-9', category: 'lover', lang: 'ko', author: '오드리 헵번', content: '가장 중요한 것은 인생을 즐기는 것, 행복해지는 것뿐이다.' },
  { id: 'q-lov-9e', category: 'lover', lang: 'en', author: 'Audrey Hepburn', content: 'The most important thing is to enjoy your life - to be happy - it\'s all that matters.' },
  { id: 'q-lov-10', category: 'lover', lang: 'ko', author: '에리히 프롬', content: '사랑은 수동적인 감정이 아니라 활동이다.' },
  { id: 'q-lov-10e', category: 'lover', lang: 'en', author: 'Erich Fromm', content: 'Love is an action, a check-the-facts activity, not a passive affect.' },

  // New Start
  { id: 'q-sta-1', category: 'new_start', lang: 'ko', author: '알베르트 아인슈타인', content: '인생은 자전거를 타는 것과 같다. 균형을 잡으려면 움직여야 한다.' },
  { id: 'q-sta-1e', category: 'new_start', lang: 'en', author: 'Albert Einstein', content: 'Life is like riding a bicycle. To keep your balance, you must keep moving.' },
  { id: 'q-sta-2', category: 'new_start', lang: 'ko', author: '월트 디즈니', content: '꿈을 꿀 수 있다면, 그것을 실현할 수도 있다.' },
  { id: 'q-sta-2e', category: 'new_start', lang: 'en', author: 'Walt Disney', content: 'If you can dream it, you can do it.' },
  { id: 'q-sta-3', category: 'new_start', lang: 'ko', author: '소포클레스', content: '성공은 그 결과가 아니라, 그 과정에서 얻는 즐거움이다.' },
  { id: 'q-sta-3e', category: 'new_start', lang: 'en', author: 'Sophocles', content: 'Success is not a destination, but the joy of the journey itself.' },
  { id: 'q-sta-4', category: 'new_start', lang: 'ko', author: '조지 엘리엇', content: '당신이 되고 싶었던 존재가 되기에 너무 늦은 때란 없다.' },
  { id: 'q-sta-4e', category: 'new_start', lang: 'en', author: 'George Eliot', content: 'It is never too late to be what you might have been.' },
  { id: 'q-sta-5', category: 'new_start', lang: 'ko', author: '윈스턴 처칠', content: '성공이란 열정을 잃지 않고 실패를 거듭하는 능력이다.' },
  { id: 'q-sta-5e', category: 'new_start', lang: 'en', author: 'Winston Churchill', content: 'Success is stumbling from failure to failure with no loss of enthusiasm.' },
  { id: 'q-sta-6', category: 'new_start', lang: 'ko', author: '스티브 잡스', content: '위대한 일을 하는 유일한 방법은 당신이 하는 일을 사랑하는 것이다.' },
  { id: 'q-sta-6e', category: 'new_start', lang: 'en', author: 'Steve Jobs', content: 'The only way to do great work is to love what you do.' },
  { id: 'q-sta-7', category: 'new_start', lang: 'ko', author: '마크 트웨인', content: '앞서가는 비결은 시작하는 것이다.' },
  { id: 'q-sta-7e', category: 'new_start', lang: 'en', author: 'Mark Twain', content: 'The secret of getting ahead is getting started.' },
  { id: 'q-sta-8', category: 'new_start', lang: 'ko', author: '랄프 왈도 에머슨', content: '길이 있는 곳으로 가지 말고, 길이 없는 곳으로 가서 발자취를 남겨라.' },
  { id: 'q-sta-8e', category: 'new_start', lang: 'en', author: 'Ralph Waldo Emerson', content: 'Do not go where the path may lead, go instead where there is no path and leave a trail.' },
  { id: 'q-sta-9', category: 'new_start', lang: 'ko', author: '헬렌 켈러', content: '세상은 고통으로 가득하지만, 한편으로는 그것을 이겨내는 일로도 가득하다.' },
  { id: 'q-sta-9e', category: 'new_start', lang: 'en', author: 'Helen Keller', content: 'Although the world is full of suffering, it is also full of the overcoming of it.' },
  { id: 'q-sta-10', category: 'new_start', lang: 'ko', author: '컨퓨셔스', content: '멈추지 않는다면 얼마나 천천히 가느냐는 중요하지 않다.' },
  { id: 'q-sta-10e', category: 'new_start', lang: 'en', author: 'Confucius', content: 'It does not matter how slowly you go as long as you do not stop.' },

  // Achievement
  { id: 'q-ach-1', category: 'achievement', lang: 'ko', author: '토마스 에디슨', content: '천재는 1%의 영감과 99%의 노력으로 이루어진다.' },
  { id: 'q-ach-1e', category: 'achievement', lang: 'en', author: 'Thomas Edison', content: 'Genius is one percent inspiration and ninety-nine percent perspiration.' },
  { id: 'q-ach-2', category: 'achievement', lang: 'ko', author: '나폴레이용', content: '불가능은 오직 바보들의 사전에서만 찾을 수 있는 단어다.' },
  { id: 'q-ach-2e', category: 'achievement', lang: 'en', author: 'Napoleon Bonaparte', content: 'The word impossible is not in my dictionary.' },
  { id: 'q-ach-3', category: 'achievement', lang: 'ko', author: '헨리 포드', content: '당신이 할 수 있다고 생각하든 할 수 없다고 생각하든, 당신의 생각은 옳다.' },
  { id: 'q-ach-3e', category: 'achievement', lang: 'en', author: 'Henry Ford', content: 'Whether you think you can, or you think you can\'t – you\'re right.' },
  { id: 'q-ach-4', category: 'achievement', lang: 'ko', author: '페르디낭 포슈', content: '가장 어두운 밤도 언젠가는 끝나고 해가 뜰 것이다.' },
  { id: 'q-ach-4e', category: 'achievement', lang: 'en', author: 'Ferdinand Foch', content: 'The darkest hour has only sixty minutes.' },
  { id: 'q-ach-5', category: 'achievement', lang: 'ko', author: '피터 드러커', content: '미래를 예측하는 가장 좋은 방법은 미래를 창조하는 것이다.' },
  { id: 'q-ach-5e', category: 'achievement', lang: 'en', author: 'Peter Drucker', content: 'The best way to predict the future is to create it.' },
  { id: 'q-ach-6', category: 'achievement', lang: 'ko', author: '아리스토텔레스', content: '우리는 우리가 반복적으로 하는 행위의 결과이다. 탁월함은 행동이 아니라 습관이다.' },
  { id: 'q-ach-6e', category: 'achievement', lang: 'en', author: 'Aristotle', content: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' },
  { id: 'q-ach-7', category: 'achievement', lang: 'ko', author: '미켈란젤로', content: '가장 큰 위험은 꿈을 높게 잡고 실패하는 것이 아니라, 낮게 잡고 달성하는 것이다.' },
  { id: 'q-ach-7e', category: 'achievement', lang: 'en', author: 'Michelangelo', content: 'The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark.' },
  { id: 'q-ach-8', category: 'achievement', lang: 'ko', author: '로자 룩셈부르크', content: '움직이지 않는 사람은 자신이 묶여 있다는 사실을 결코 알 수 없다.' },
  { id: 'q-ach-8e', category: 'achievement', lang: 'en', author: 'Rosa Luxemburg', content: 'Those who do not move, do not notice their chains.' },
  { id: 'q-ach-9', category: 'achievement', lang: 'ko', author: '비달 사순', content: '사전에서 성공(Success)이 노력(Work)보다 앞에 나오는 유일한 곳은 사전뿐이다.' },
  { id: 'q-ach-9e', category: 'achievement', lang: 'en', author: 'Vidal Sassoon', content: 'The only place where success comes before work is in the dictionary.' },
  { id: 'q-ach-10', category: 'achievement', lang: 'ko', author: '파울로 코엘료', content: '무언가를 간절히 원할 때 전 우주는 당신의 소망이 실현되도록 도와준다.' },
  { id: 'q-ach-10e', category: 'achievement', lang: 'en', author: 'Paulo Coelho', content: 'And, when you want something, all the universe conspires in helping you to achieve it.' },

  // Wedding/Anniversary
  { id: 'q-wed-1', category: 'wedding', lang: 'ko', author: '마틴 루터', content: '세상에는 가정보다 더 행복하고 신성한 곳은 없다.' },
  { id: 'q-wed-1e', category: 'wedding', lang: 'en', author: 'Martin Luther', content: 'There is no more lovely, friendly and charming relationship, communion or company than a good marriage.' },
  { id: 'q-wed-2', category: 'wedding', lang: 'ko', author: '니체', content: '행복한 결혼은 긴 대화와 같다. 항상 너무 짧게 느껴지는.' },
  { id: 'q-wed-2e', category: 'wedding', lang: 'en', author: 'Friedrich Nietzsche', content: 'It is not a lack of love, but a lack of friendship that makes unhappy marriages.' },
  { id: 'q-wed-3', category: 'wedding', lang: 'ko', author: '생텍쥐페리', content: '사랑은 서로 마주 보는 것이 아니라, 함께 같은 방향을 보는 것이다.' },
  { id: 'q-wed-3e', category: 'wedding', lang: 'en', author: 'Saint-Exupery', content: 'To love is not to look at one another, but to look together in the same direction.' },
  { id: 'q-wed-4', category: 'wedding', lang: 'ko', author: '미상', content: '결혼은 인생의 목적이 아니라, 인생이라는 여행을 함께할 동반자를 만나는 것이다.' },
  { id: 'q-wed-4e', category: 'wedding', lang: 'en', author: 'Anonymous', content: 'Marriage is not a destination, but a beautiful journey shared by two souls.' },
  { id: 'q-wed-5', category: 'wedding', lang: 'ko', author: '레프 톨스토이', content: '행복한 가정은 모두 엇비슷하고, 불행한 가정은 불행한 이유가 제각기 다르다.' },
  { id: 'q-wed-5e', category: 'wedding', lang: 'en', author: 'Leo Tolstoy', content: 'All happy families are alike; each unhappy family is unhappy in its own way.' },
  { id: 'q-wed-6', category: 'wedding', lang: 'ko', author: '마크 트웨인', content: '사랑은 눈부시게 아름답지만, 우정은 그보다 더 오래 지속된다.' },
  { id: 'q-wed-6e', category: 'wedding', lang: 'en', author: 'Mark Twain', content: 'Love is the swift transition from content to joy, while friendship is the steady glow of warmth.' },
  { id: 'q-wed-7', category: 'wedding', lang: 'ko', author: '에밀리 디킨슨', content: '사랑은 불멸이다. 왜냐하면 그것은 신의 그림자이기 때문이다.' },
  { id: 'q-wed-7e', category: 'wedding', lang: 'en', author: 'Emily Dickinson', content: 'That love is all there is, is all we know of love.' },
  { id: 'q-wed-8', category: 'wedding', lang: 'ko', author: '헤르만 헤세', content: '사랑을 하는 것은 곧 행복의 원천을 발견하는 것이다.' },
  { id: 'q-wed-8e', category: 'wedding', lang: 'en', author: 'Hermann Hesse', content: 'Love is the reason for all things. To love is to find the source of joy.' },
  { id: 'q-wed-9', category: 'wedding', lang: 'ko', author: '소크라테스', content: '반드시 결혼하라. 좋은 아내를 얻으면 행복할 것이고, 나쁜 아내를 얻으면 철학자가 될 것이다.' },
  { id: 'q-wed-9e', category: 'wedding', lang: 'en', author: 'Socrates', content: 'By all means, marry. If you get a good wife, you\'ll become happy; if you get a bad one, you\'ll become a philosopher.' },
  { id: 'q-wed-10', category: 'wedding', lang: 'ko', author: '로버트 스티븐슨', content: '결혼은 어느 한 쪽이 희생하는 것이 아니라, 두 사람이 하나로 합쳐지는 예술이다.' },
  { id: 'q-wed-10e', category: 'wedding', lang: 'en', author: 'Robert Louis Stevenson', content: 'Marriage is a step so grave and decisive that it attracts light-headed, variable men by its very awfulness.' },

  // Respect/Gratitude
  { id: 'q-res-1', category: 'respect', lang: 'ko', author: '키케로', content: '감사는 최고의 덕일 뿐만 아니라 모든 덕의 어머니이다.' },
  { id: 'q-res-1e', category: 'respect', lang: 'en', author: 'Cicero', content: 'Gratitude is not only the greatest of virtues, but the parent of all others.' },
  { id: 'q-res-2', category: 'respect', lang: 'ko', author: '알베르트 슈바이처', content: '감사하는 마음은 축복의 문을 여는 열쇠이다.' },
  { id: 'q-res-2e', category: 'respect', lang: 'en', author: 'Albert Schweitzer', content: 'At times our own light goes out and is rekindled by a spark from another person.' },
  { id: 'q-res-3', category: 'respect', lang: 'ko', author: '미상', content: '존경은 얻는 것이 아니라 고취시키는 것이다.' },
  { id: 'q-res-3e', category: 'respect', lang: 'en', author: 'Anonymous', content: 'Respect is earned, honesty is appreciated, trust is gained, and loyalty is returned.' },
  { id: 'q-res-4', category: 'respect', lang: 'ko', author: '볼테르', content: '우리는 우리가 가진 것에 감사해야 한다. 그러면 더 많은 것을 얻게 될 것이다.' },
  { id: 'q-res-4e', category: 'respect', lang: 'en', author: 'Voltaire', content: 'Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.' },
  { id: 'q-res-5', category: 'respect', lang: 'ko', author: '요한 길버트', content: '감사는 가장 우아한 예절이다.' },
  { id: 'q-res-5e', category: 'respect', lang: 'en', author: 'Yvonne Gilbert', content: 'Gratitude is the most exquisite form of courtesy.' },
  { id: 'q-res-6', category: 'respect', lang: 'ko', author: '윌리엄 워즈워스', content: '감사하는 마음은 지혜의 시작이다.' },
  { id: 'q-res-6e', category: 'respect', lang: 'en', author: 'William Wordsworth', content: 'Gratitude is the memory of the heart.' },
  { id: 'q-res-7', category: 'respect', lang: 'ko', author: '오프라 윈프리', content: '당신이 가진 것에 감사하면 당신은 결국 더 많이 가지게 될 것이다.' },
  { id: 'q-res-7e', category: 'respect', lang: 'en', author: 'Oprah Winfrey', content: 'Be thankful for what you have; you\'ll end up having more.' },
  { id: 'q-res-8', category: 'respect', lang: 'ko', author: '프란츠 카프카', content: '진정한 존경은 상대방의 자유를 존중하는 데서 시작된다.' },
  { id: 'q-res-8e', category: 'respect', lang: 'en', author: 'Franz Kafka', content: 'Paths are made by walking. True respect is seeing the path of others.' },
  { id: 'q-res-9', category: 'respect', lang: 'ko', author: '피타고라스', content: '존경받는 비결은 남을 존경하는 데 있다.' },
  { id: 'q-res-9e', category: 'respect', lang: 'en', author: 'Pythagoras', content: 'Respect yourself and others will respect you.' },
  { id: 'q-res-10', category: 'respect', lang: 'ko', author: '존 밀턴', content: '누군가에게 감사를 표현하는 것은 그 사람의 가치를 인정하는 것이다.' },
  { id: 'q-res-10e', category: 'respect', lang: 'en', author: 'John Milton', content: 'Gratitude bestows reverence, allowing us to encounter everyday epiphanies.' },

  // Family/Parents
  { id: 'q-fam-1', category: 'family', lang: 'ko', author: '에이브러햄 링컨', content: '내가 오늘날의 위치에 있게 된 것은 모두 어머니 덕분이다.' },
  { id: 'q-fam-1e', category: 'family', lang: 'en', author: 'Abraham Lincoln', content: 'All that I am, or hope to be, I owe to my angel mother.' },
  { id: 'q-fam-2', category: 'family', lang: 'ko', author: '에우리피데스', content: '자식은 부모의 인생을 완성하는 존재다.' },
  { id: 'q-fam-2e', category: 'family', lang: 'en', author: 'Euripides', content: 'To a father growing old, nothing is dearer than a daughter.' },
  { id: 'q-fam-3', category: 'family', lang: 'ko', author: '장 자크 루소', content: '가정은 국가의 기초다.' },
  { id: 'q-fam-3e', category: 'family', lang: 'en', author: 'Jean-Jacques Rousseau', content: 'The first of all societies is the family.' },
  { id: 'q-fam-4', category: 'family', lang: 'ko', author: '마크 트웨인', content: '나이가 들수록 부모님의 조언이 얼마나 정확했는지 깨닫게 된다.' },
  { id: 'q-fam-4e', category: 'family', lang: 'en', author: 'Mark Twain', content: 'When I was a boy of 14, my father was so ignorant... but when I got to be 21, I was astonished at how much the old man had learned.' },
  { id: 'q-fam-5', category: 'family', lang: 'ko', author: '조지 산타야나', content: '가족은 자연이 만든 가장 위대한 걸작 중 하나다.' },
  { id: 'q-fam-5e', category: 'family', lang: 'en', author: 'George Santayana', content: 'The family is one of nature\'s masterpieces.' },
  { id: 'q-fam-6', category: 'family', lang: 'ko', author: '데스몬드 투투', content: '가족은 신이 우리에게 준 선물이다.' },
  { id: 'q-fam-6e', category: 'family', lang: 'en', author: 'Desmond Tutu', content: 'You don\'t choose your family. They are God\'s gift to you.' },
  { id: 'q-fam-7', category: 'family', lang: 'ko', author: '미상', content: '부모님의 사랑은 바다보다 깊고 하늘보다 높다.' },
  { id: 'q-fam-7e', category: 'family', lang: 'en', author: 'Anonymous', content: 'A parent\'s love is whole no matter how many times divided.' },
  { id: 'q-fam-8', category: 'family', lang: 'ko', author: '프랜시스 베이컨', content: '가정의 행복은 이 세상의 가장 큰 기쁨이다.' },
  { id: 'q-fam-8e', category: 'family', lang: 'en', author: 'Francis Bacon', content: 'The joys of parents are secret, and so are their griefs and fears.' },
  { id: 'q-fam-9', category: 'family', lang: 'ko', author: '마야 안젤루', content: '가족은 휴식처이자 폭풍우 속의 안식처다.' },
  { id: 'q-fam-9e', category: 'family', lang: 'en', author: 'Maya Angelou', content: 'I sustain myself with the love of family.' },
  { id: 'q-fam-10', category: 'family', lang: 'ko', author: '바바라 부시', content: '결국 소중한 것은 얼마나 화려하게 살았느냐가 아니라, 얼마나 사랑했느냐이다.' },
  { id: 'q-fam-10e', category: 'family', lang: 'en', author: 'Barbara Bush', content: 'At the end of your life, you will never regret not having passed one more test, but you will regret not spending time with family.' }
];

/**
 * Suggested Messages for the Right Page (The Letter content)
 */
export const MESSAGE_SUGGESTIONS: ContentSuggestion[] = [
  // Lover
  { id: 'm-lov-1', category: 'lover', lang: 'ko', content: '당신과 함께라면 어디든 꽃길일 것 같아요. 오늘도 내 곁에 있어줘서 고마워요.' },
  { id: 'm-lov-1e', category: 'lover', lang: 'en', content: 'With you, anywhere feels like a flower path. Thank you for being by my side today.' },
  { id: 'm-lov-2', category: 'lover', lang: 'ko', content: '세상에서 가장 예쁜 꽃을 당신에게 드려요. 당신의 미소가 내 세상의 전부입니다.' },
  { id: 'm-lov-2e', category: 'lover', lang: 'en', content: 'I give you the prettiest flower in the world. Your smile is my everything.' },
  { id: 'm-lov-3', category: 'lover', lang: 'ko', content: '우리가 함께한 시간만큼 이 꽃의 향기도 진해지길 바래요. 영원히 사랑해.' },
  { id: 'm-lov-3e', category: 'lover', lang: 'en', content: 'I hope the scent of this flower deepens as much as the time we spent together. I love you forever.' },
  { id: 'm-lov-4', category: 'lover', lang: 'ko', content: '특별한 날이 아니어도 당신에게 꽃을 선물하고 싶었어요. 당신은 존재 자체로 특별하니까요.' },
  { id: 'm-lov-4e', category: 'lover', lang: 'en', content: 'I wanted to give you flowers even if it’s not a special day. Because you are special just as you are.' },
  { id: 'm-lov-5', category: 'lover', lang: 'ko', content: '꽃잎 하나하나가 당신을 향한 내 마음이에요. 오늘도 행복한 하루 보내요, 내 사랑.' },
  { id: 'm-lov-5e', category: 'lover', lang: 'en', content: 'Each petal represents my feelings for you. Have a happy day today, my love.' },
  { id: 'm-lov-6', category: 'lover', lang: 'ko', content: '눈을 뜨면 당신 생각이 가장 먼저 나요. 이 꽃처럼 화사한 하루가 되길.' },
  { id: 'm-lov-6e', category: 'lover', lang: 'en', content: 'You are my first thought when I wake up. Wishing you a bright day like these flowers.' },
  { id: 'm-lov-7', category: 'lover', lang: 'ko', content: '고마워요, 내 부족한 부분을 채워주는 당신이 있어서 참 다행이에요.' },
  { id: 'm-lov-7e', category: 'lover', lang: 'en', content: 'Thank you for being there to fill my shortcomings. I’m so lucky to have you.' },
  { id: 'm-lov-8', category: 'lover', lang: 'ko', content: '우리의 사랑이 이 꽃들처럼 아름답게 피어나길 약속해요. 많이 사랑합니다.' },
  { id: 'm-lov-8e', category: 'lover', lang: 'en', content: 'I promise our love will bloom as beautifully as these flowers. I love you so much.' },
  { id: 'm-lov-9', category: 'lover', lang: 'ko', content: '당신이라는 꽃을 만난 것이 내 인생 최대의 행운입니다. 내 곁에 오래 머물러줘요.' },
  { id: 'm-lov-9e', category: 'lover', lang: 'en', content: 'Meeting a flower like you is the greatest luck of my life. Please stay with me for a long time.' },
  { id: 'm-lov-10', category: 'lover', lang: 'ko', content: '세상 모든 예쁜 것들을 다 합쳐도 당신에겐 못 미치죠. 오늘도 예쁜 꿈 꿔요.' },
  { id: 'm-lov-10e', category: 'lover', lang: 'en', content: 'Even all the pretty things in the world combined cannot compare to you. Have sweet dreams today.' },

  // New Start
  { id: 'm-sta-1', category: 'new_start', lang: 'ko', content: '새로운 도전에 박수를 보냅니다! 당신의 용기 있는 시작이 멋진 결과로 이어질 거예요.' },
  { id: 'm-sta-1e', category: 'new_start', lang: 'en', content: 'Applause for your new challenge! Your courageous start will lead to wonderful results.' },
  { id: 'm-sta-2', category: 'new_start', lang: 'ko', content: '낯선 길의 시작이지만, 당신의 열정이라면 분명 잘 해낼 거예요. 언제나 응원할게요.' },
  { id: 'm-sta-2e', category: 'new_start', lang: 'en', content: 'It’s the start of an unfamiliar path, but with your passion, you’ll definitely do well. I’ll always support you.' },
  { id: 'm-sta-3', category: 'new_start', lang: 'ko', content: '두근거리는 시작을 축하드려요! 당신의 앞날이 이 꽃처럼 활짝 피어나길 응원합니다.' },
  { id: 'm-sta-3e', category: 'new_start', lang: 'en', content: 'Congratulations on your exciting start! Rooting for your future to bloom wide like these flowers.' },
  { id: 'm-sta-4', category: 'new_start', lang: 'ko', content: '실패를 두려워하지 않는 당신의 도전을 응원해요. 당신은 이미 충분히 빛나고 있어요.' },
  { id: 'm-sta-4e', category: 'new_start', lang: 'en', content: 'Cheering for your challenge without fear of failure. You are already shining enough.' },
  { id: 'm-sta-5', category: 'new_start', lang: 'ko', content: '새로운 환경에서도 당신의 능력을 마음껏 펼치시길 바랍니다. 당당하게 나아가세요!' },
  { id: 'm-sta-5e', category: 'new_start', lang: 'en', content: 'I hope you display your abilities to your heart’s content in your new environment. Move forward with confidence!' },
  { id: 'm-sta-6', category: 'new_start', lang: 'ko', content: '꿈을 향해 한 걸음 더 다가선 당신이 자랑스러워요. 이 꽃들이 당신의 길을 비춰주길.' },
  { id: 'm-sta-6e', category: 'new_start', lang: 'en', content: 'I’m proud of you for taking another step toward your dream. May these flowers light up your path.' },
  { id: 'm-sta-7', category: 'new_start', lang: 'ko', content: '새로운 시작을 진심으로 축하하며, 항상 긍정적인 에너지가 가득하길 기원합니다.' },
  { id: 'm-sta-7e', category: 'new_start', lang: 'en', content: 'Heartfelt congratulations on your new beginning, and wishing you lots of positive energy always.' },
  { id: 'm-sta-8', category: 'new_start', lang: 'ko', content: '당신의 새로운 챕터가 행복한 이야기로 가득 채워지길 바랍니다. 화이팅!' },
  { id: 'm-sta-8e', category: 'new_start', lang: 'en', content: 'I hope your new chapter is filled with happy stories. You can do it!' },
  { id: 'm-sta-9', category: 'new_start', lang: 'ko', content: '그토록 원하던 시작이네요. 당신의 꿈이 현실이 되는 과정을 곁에서 지켜보며 응원할게요.' },
  { id: 'm-sta-9e', category: 'new_start', lang: 'en', content: 'The start you wanted so much. I\'ll watch and cheer as your dream becomes reality.' },
  { id: 'm-sta-10', category: 'new_start', lang: 'ko', content: '어떤 어려움이 와도 지금의 마음가짐을 잊지 마세요. 당신의 시작을 온 마음 다해 축하합니다.' },
  { id: 'm-sta-10e', category: 'new_start', lang: 'en', content: 'No matter what difficulties come, don\'t forget your current mindset. Heartfelt congratulations on your beginning.' },

  // Achievement/Career
  { id: 'm-ach-1', category: 'achievement', lang: 'ko', content: '승진을 축하드립니다! 그동안의 성실함과 노력이 맺은 값진 결실이네요.' },
  { id: 'm-ach-1e', category: 'achievement', lang: 'en', content: 'Congratulations on your promotion! It’s a precious fruit of your past diligence and effort.' },
  { id: 'm-ach-2', category: 'achievement', lang: 'ko', content: '원하던 곳으로의 이직을 축하해요. 새로운 곳에서도 당신의 실력을 유감없이 발휘하세요.' },
  { id: 'm-ach-2e', category: 'achievement', lang: 'en', content: 'Congrats on your job change to the place you wanted. Display your skills fully in your new place too.' },
  { id: 'm-ach-3', category: 'achievement', lang: 'ko', content: '하나의 목표를 성취해낸 당신이 정말 멋집니다. 다음 목표를 향한 도약도 응원할게요.' },
  { id: 'm-ach-3e', category: 'achievement', lang: 'en', content: 'You are so cool for achieving one goal. I’ll cheer for your leap toward the next goal too.' },
  { id: 'm-ach-4', category: 'achievement', lang: 'ko', content: '당신의 성공은 우연이 아닙니다. 매일 밤낮으로 노력한 결과임을 잘 알고 있어요. 축하합니다!' },
  { id: 'm-ach-4e', category: 'achievement', lang: 'en', content: 'Your success is no coincidence. I know well it’s the result of your day and night effort. Congratulations!' },
  { id: 'm-ach-5', category: 'achievement', lang: 'ko', content: '리더로서 새로운 발걸음을 떼는 당신을 응원합니다. 이 꽃들처럼 향기로운 팀을 만들어가세요.' },
  { id: 'm-ach-5e', category: 'achievement', lang: 'en', content: 'Crete a fragrant team like these flowers.' },
  { id: 'm-ach-6', category: 'achievement', lang: 'ko', content: '커리어의 빛나는 순간을 함께 축하할 수 있어 기쁩니다. 앞으로 더 높이 비상하시길.' },
  { id: 'm-ach-6e', category: 'achievement', lang: 'en', content: 'Glad to celebrate this shining moment of your career together. May you soar even higher ahead.' },
  { id: 'm-ach-7', category: 'achievement', lang: 'ko', content: '어려운 프로젝트를 성공적으로 마친 공로를 높이 평가합니다. 정말 수고 많으셨습니다!' },
  { id: 'm-ach-7e', category: 'achievement', lang: 'en', content: 'Highly appreciative of your contribution to successfully finishing the difficult project. Great job!' },
  { id: 'm-ach-8', category: 'achievement', lang: 'ko', content: '당신의 전문성과 열정이 인정받은 오늘이 정말 기쁘네요. 더 멋진 내일을 기대합니다.' },
  { id: 'm-ach-8e', category: 'achievement', lang: 'en', content: 'I’m so happy today that your expertise and passion are recognized. Looking forward to a cooler tomorrow.' },
  { id: 'm-ach-9', category: 'achievement', lang: 'ko', content: '도전 끝에 쟁취한 성취라 더욱 값진 것 같아요. 진심으로 축하의 인사를 전합니다.' },
  { id: 'm-ach-9e', category: 'achievement', lang: 'en', content: 'This achievement feels more precious as it was won after challenges. Sending heartfelt congratulations.' },
  { id: 'm-ach-10', category: 'achievement', lang: 'ko', content: '항상 묵묵히 제 자리에서 최선을 다하는 당신이 자랑스럽습니다. 승승장구하시길 기원합니다.' },
  { id: 'm-ach-10e', category: 'achievement', lang: 'en', content: 'I’m proud of you for always doing your best silently in your place. Wishing you ever-increasing success.' },

  // Wedding/Anniversary
  { id: 'm-wed-1', category: 'wedding', lang: 'ko', content: '두 사람의 아름다운 미래가 시작되는 오늘을 진심으로 축하합니다. 서로를 향한 사랑 영원히 간직하세요.' },
  { id: 'm-wed-1e', category: 'wedding', lang: 'en', content: 'Heartfelt congratulations on today, the start of your beautiful future together. Keep your love for each other forever.' },
  { id: 'm-wed-2', category: 'wedding', lang: 'ko', content: '세상에서 가장 잘 어울리는 한 쌍! 함께 걷는 그 길이 늘 꽃향기로 가득하길 바랍니다.' },
  { id: 'm-wed-2e', category: 'wedding', lang: 'en', content: 'The best-matching pair in the world! Wishing your path together is always filled with flower scents.' },
  { id: 'm-wed-3', category: 'wedding', lang: 'ko', content: '우리가 부부가 된 지 벌써 n주년이네요. 변함없이 내 곁을 지켜준 당신, 진심으로 감사하고 사랑합니다.' },
  { id: 'm-wed-3e', category: 'wedding', lang: 'en', content: 'It’s already been n years since we became a couple. Thank you so much and I love you for staying by my side invariably.' },
  { id: 'm-wed-4', category: 'wedding', lang: 'ko', content: '검은 머리 파뿌리 될 때까지, 서로의 든든한 휴식처가 되어주며 행복하게 사세요. 결혼 축하해!' },
  { id: 'm-wed-4e', category: 'wedding', lang: 'en', content: 'Live happily being each other’s strong rest area until the end. Congrats on your wedding!' },
  { id: 'm-wed-5', category: 'wedding', lang: 'ko', content: '사랑의 결실을 맺는 소중한 날, 두 분의 앞날에 축복만 가득하길 기원합니다.' },
  { id: 'm-wed-5e', category: 'wedding', lang: 'en', content: 'Wishing only blessings in your future on this precious day of love’s fruition.' },
  { id: 'm-wed-6', category: 'wedding', lang: 'ko', content: '서로를 아끼고 존중하며 예쁜 가정 꾸려나가시길 바래요. 다시 한번 축하드립니다!' },
  { id: 'm-wed-6e', category: 'wedding', lang: 'en', content: 'Hope you build a pretty family by caring for and respecting each other. Congratulations once again!' },
  { id: 'm-wed-7', category: 'wedding', lang: 'ko', content: '부부로서 내딛는 첫걸음을 축복합니다. 슬플 때나 기쁠 때나 늘 함께하며 행복하세요.' },
  { id: 'm-wed-7e', category: 'wedding', lang: 'en', content: 'Blessing your first step as a married couple. Be happy together through sad and joyful times.' },
  { id: 'm-wed-8', category: 'wedding', lang: 'ko', content: '사랑하는 나의 아내/남편에게, 당신과 함께 늙어가는 이 모든 순간이 나에겐 축복이에요.' },
  { id: 'm-wed-8e', category: 'wedding', lang: 'en', content: 'To my loving wife/husband, all these moments growing old with you are a blessing to me.' },
  { id: 'm-wed-9', category: 'wedding', lang: 'ko', content: '두 분의 결합이 이 꽃들처럼 화사한 삶으로 이어지길 바랍니다. 결혼 진심으로 축하해요.' },
  { id: 'm-wed-9e', category: 'wedding', lang: 'en', content: 'Wishing your union leads to a life as bright as these flowers. Heartfelt congrats on your marriage.' },
  { id: 'm-wed-10', category: 'wedding', lang: 'ko', content: '세상 어떤 말로도 부족한 나의 사랑, 오늘 우리 결혼 기념일을 진심으로 축하해. 사랑해.' },
  { id: 'm-wed-10e', category: 'wedding', lang: 'en', content: 'My love, which cannot be expressed with any words, heartfelt congratulations on our wedding anniversary today. I love you.' },

  // Respect/Gratitude
  { id: 'm-res-1', category: 'respect', lang: 'ko', content: '베풀어주신 따뜻한 가르침 잊지 않겠습니다. 존경하는 선생님/선배님, 항상 건강하세요.' },
  { id: 'm-res-1e', category: 'respect', lang: 'en', content: 'I won’t forget the warm teachings you bestowed. Respected teacher/senior, stay healthy always.' },
  { id: 'm-res-2', category: 'respect', lang: 'ko', content: '힘든 시기에 주신 격려와 응원 덕분에 잘 이겨낼 수 있었습니다. 깊은 감사의 마음을 전합니다.' },
  { id: 'm-res-2e', category: 'respect', lang: 'en', content: 'I could overcome it well thanks to the encouragement and support you gave during hard times. Deep gratitude to you.' },
  { id: 'm-res-3', category: 'respect', lang: 'ko', content: '언제나 묵묵히 제 뒤에서 든든한 버팀목이 되어주셔서 감사합니다. 존경하고 사랑합니다.' },
  { id: 'm-res-3e', category: 'respect', lang: 'en', content: 'Thank you for always being a strong support behind me. I respect and love you.' },
  { id: 'm-res-4', category: 'respect', lang: 'ko', content: '보내주신 큰 사랑에 보답할 수 있도록 더욱 노력하겠습니다. 이 꽃과 함께 감사의 인사를 드립니다.' },
  { id: 'm-res-4e', category: 'respect', lang: 'en', content: 'I’ll strive more to repay the great love you sent. Sending gratitude with these flowers.' },
  { id: 'm-res-5', category: 'respect', lang: 'ko', content: '선생님의 가르침이 제 인생의 큰 이정표가 되었습니다. 스승의 은혜에 깊이 감사드립니다.' },
  { id: 'm-res-5e', category: 'respect', lang: 'en', content: 'Your teachings became a great milestone in my life. Deeply grateful for your grace, Teacher.' },
  { id: 'm-res-6', category: 'respect', lang: 'ko', content: '말로 다 표현할 수 없는 고마움을 담아 이 편지를 씁니다. 항상 곁에 있어주셔서 감사해요.' },
  { id: 'm-res-6e', category: 'respect', lang: 'en', content: 'Writing this letter with gratitude that cannot be expressed. Thank you for always being there.' },
  { id: 'm-res-7', category: 'respect', lang: 'ko', content: '당신의 헌신과 열정은 저에게 언제나 큰 귀감이 됩니다. 존경하는 마음을 담아 꽃을 보냅니다.' },
  { id: 'm-res-7e', category: 'respect', lang: 'en', content: 'Your dedication and passion are always a great role model for me. Sending flowers with respect.' },
  { id: 'm-res-8', category: 'respect', lang: 'ko', content: '작은 정성이지만 제 감사의 마음이 잘 전달되었으면 좋겠습니다. 정말 고맙습니다.' },
  { id: 'm-res-8e', category: 'respect', lang: 'en', content: 'It’s a small token, but I hope my gratitude is well delivered. Thank you so much.' },
  { id: 'm-res-9', category: 'respect', lang: 'ko', content: '오늘의 제가 있기까지 보내주신 무한한 신뢰와 지지에 감사드립니다. 잊지 않겠습니다.' },
  { id: 'm-res-9e', category: 'respect', lang: 'en', content: 'Thank you for the infinite trust and support you gave for me to be who I am today. I won’t forget.' },
  { id: 'm-res-10', category: 'respect', lang: 'ko', content: '함께해주신 모든 순간들이 저에겐 큰 배움이었습니다. 앞으로도 많은 지도 편달 부탁드립니다.' },
  { id: 'm-res-10e', category: 'respect', lang: 'en', content: 'All the moments we spent together were a great learning for me. Please continue to guide me.' },

  // Family/Parents
  { id: 'm-fam-1', category: 'family', lang: 'ko', content: '사랑하는 부모님, 낳아주시고 길러주셔서 감사합니다. 두 분의 깊은 사랑에 조금이나마 보답하고 싶어요.' },
  { id: 'm-fam-1e', category: 'family', lang: 'en', content: 'Dear parents, thank you for giving birth to and raising me. I want to repay your deep love even a little.' },
  { id: 'm-fam-2', category: 'family', lang: 'ko', content: '세상에서 가장 존경하는 어머니, 아버지. 두 분이 계셔서 저는 항상 든든하고 행복합니다. 사랑해요.' },
  { id: 'm-fam-2e', category: 'family', lang: 'en', content: 'The most respected Mom and Dad in the world. I’m always strong and happy because of you. Love you.' },
  { id: 'm-fam-3', category: 'family', lang: 'ko', content: '부모님의 은혜를 이 꽃 한 송이에 담기엔 부족하지만, 제 마음만은 꼭 전달되길 바래요.' },
  { id: 'm-fam-3e', category: 'family', lang: 'en', content: 'This one flower isn’t enough to hold your grace, but I hope my feelings are delivered.' },
  { id: 'm-fam-4', category: 'family', lang: 'ko', content: '늘 자식 걱정뿐인 우리 엄마 아빠, 이제는 본인들의 행복도 챙기며 사셨으면 좋겠어요. 건강하세요!' },
  { id: 'm-fam-4e', category: 'family', lang: 'en', content: 'To my Mom and Dad who only worry about their kids, I hope you now live taking care of your own happiness. Stay healthy!' },
  { id: 'm-fam-5', category: 'family', lang: 'ko', content: '부모님이라는 큰 나무 아래서 제가 이렇게 잘 자랄 수 있었습니다. 사랑하고 또 사랑합니다.' },
  { id: 'm-fam-5e', category: 'family', lang: 'en', content: 'I could grow up well under the big tree called parents. I love and love you more.' },
  { id: 'm-fam-6', category: 'family', lang: 'ko', content: '부족한 딸/아들이지만 항상 믿어주셔서 감사해요. 자랑스러운 자식이 되도록 노력할게요.' },
  { id: 'm-fam-6e', category: 'family', lang: 'en', content: 'Thank you for always believing in me, despite my shortcomings. I’ll strive to be a child you can be proud of.' },
  { id: 'm-fam-7', category: 'family', lang: 'ko', content: '어버이날을 맞아 평소 쑥스러워 하지 못했던 말을 전합니다. 엄마 아빠, 정말 사랑합니다!' },
  { id: 'm-fam-7e', category: 'family', lang: 'en', content: 'On Parents’ Day, I say the words I was too shy to say. Mom and Dad, I really love you!' },
  { id: 'm-fam-8', category: 'family', lang: 'ko', content: '우리 가족, 언제나 지금처럼 서로 아끼고 사랑하며 행복하게 살아요. 당신들이 있기에 제가 웃습니다.' },
  { id: 'm-fam-8e', category: 'family', lang: 'en', content: 'Our family, let’s live happily caring for and loving each other like now. I laugh because of you.' },
  { id: 'm-fam-9', category: 'family', lang: 'ko', content: '부모님의 가르침대로 바르게 살아가겠습니다. 두 분의 건강과 행복이 저의 가장 큰 소망입니다.' },
  { id: 'm-fam-9e', category: 'family', lang: 'en', content: 'I will live upright following your teachings. Your health and happiness are my greatest wishes.' },
  { id: 'm-fam-10', category: 'family', lang: 'ko', content: '사랑해요 엄마 아빠! 표현은 서툴러도 제 마음 속엔 항상 부모님이 1순위인 거 아시죠? 고마워요.' },
  { id: 'm-fam-10e', category: 'family', lang: 'en', content: 'Love you, Mom and Dad! You know you are always my priority even if I’m bad at expressing it, right? Thanks.' }
];
