import {
  DEFAULT_EXPENSE_CATEGORIES,
  DEFAULT_MATERIAL_CATEGORIES,
  DEFAULT_PRODUCT_CATEGORIES,
} from "@/lib/category-defaults";
import type { TenantMasterSeed } from "../types";

/**
 * 표준 시드 v2026-04-21 — 앱 기본 카테고리 + 샘플 마스터(최소 20건 단위로 구성).
 * 실제 운영 품목·단가는 매장에서 수정·확정.
 */
export const TENANT_MASTER_SEED_V2026_04_21: TenantMasterSeed = {
  version: "v2026-04-21",
  label: "표준 초기 세팅 (카테고리 기본 + 샘플 마스터)",
  productCategories: DEFAULT_PRODUCT_CATEGORIES,
  materialCategories: DEFAULT_MATERIAL_CATEGORIES,
  expenseCategories: DEFAULT_EXPENSE_CATEGORIES,
  suppliers: [
    {
      name: "릴리맥 NC (샘플)",
      memo: "시드로 넣은 샘플 거래처입니다. 실제 정보로 수정하세요.",
      supplier_type: "생화",
    },
    {
      name: "이스트폴 협력사 (샘플)",
      memo: "시드 샘플. 사업자번호·연락처는 직접 등록하세요.",
      supplier_type: "부자재",
    },
    { name: "양재 도매 A (샘플)", supplier_type: "생화", memo: "샘플" },
    { name: "화훼자재 B (샘플)", supplier_type: "화훼부자재", memo: "샘플" },
    { name: "분화 농원 C (샘플)", supplier_type: "분화", memo: "샘플" },
    { name: "포장재 도매 D (샘플)", supplier_type: "부자재", memo: "샘플" },
    { name: "플라스틱 화기 E (샘플)", supplier_type: "부자재", memo: "샘플" },
    { name: "리본·텍 F (샘플)", supplier_type: "부자재", memo: "샘플" },
    { name: "조화 도매 G (샘플)", supplier_type: "부자재", memo: "샘플" },
    { name: "프리저브드 H (샘플)", supplier_type: "부자재", memo: "샘플" },
    { name: "배송·택배 I (샘플)", supplier_type: "기타공급업체", memo: "샘플" },
    { name: "사무·잡화 J (샘플)", supplier_type: "기타공급업체", memo: "샘플" },
    { name: "식음료 협력 K (샘플)", supplier_type: "식당", memo: "샘플" },
    { name: "인쇄·간판 L (샘플)", supplier_type: "기타공급업체", memo: "샘플" },
    { name: "냉장 설비 M (샘플)", supplier_type: "기타공급업체", memo: "샘플" },
    { name: "비료·원예 N (샘플)", supplier_type: "분화", memo: "샘플" },
    { name: "수입 생화 O (샘플)", supplier_type: "생화", memo: "샘플" },
    { name: "국산 생화 P (샘플)", supplier_type: "생화", memo: "샘플" },
    { name: "바구니·라탄 Q (샘플)", supplier_type: "부자재", memo: "샘플" },
    { name: "유리·도자기 R (샘플)", supplier_type: "부자재", memo: "샘플" },
  ],
  products: [
    {
      name: "장미 꽃다발 기본형(샘플)",
      main_category: "꽃다발",
      mid_category: "기본형",
      code: "SAMPLE-BOUQUET-ROSE-BASIC",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "카네이션 바구니 M(샘플)",
      main_category: "꽃바구니",
      mid_category: "M사이즈",
      code: "SAMPLE-BASKET-CARN-M",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "축하 화환 3단(샘플)",
      main_category: "경조사화환",
      mid_category: "축하 3단",
      code: "SAMPLE-WREATH-CONGRATS-3",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "호접란(샘플)",
      main_category: "서양란",
      mid_category: "호접란",
      code: "SAMPLE-ORCHID-PHAL",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "관엽 소품(샘플)",
      main_category: "식물/화분",
      mid_category: "관엽",
      code: "SAMPLE-PLANT-FOLIAGE-S",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "핑크 장미 꽃다발 대형(샘플)",
      main_category: "꽃다발",
      mid_category: "대형",
      code: "SAMPLE-BOUQUET-ROSE-L",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "한 송이 장미(샘플)",
      main_category: "꽃다발",
      mid_category: "한송이",
      code: "SAMPLE-BOUQUET-SINGLE",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "플라워 박스 S(샘플)",
      main_category: "기프티콘/기프트상품",
      mid_category: "플라워박스",
      code: "SAMPLE-BOX-FLOWER-S",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "근조 화환 3단(샘플)",
      main_category: "경조사화환",
      mid_category: "근조 3단",
      code: "SAMPLE-WREATH-FUNERAL-3",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "어버이날 카네이션 박스(샘플)",
      main_category: "어버이날상품",
      mid_category: "카네이션 박스",
      code: "SAMPLE-PARENTS-CARN-BOX",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "동양란 분재(샘플)",
      main_category: "동양란",
      mid_category: "동양란",
      code: "SAMPLE-ORCHID-EAST",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "공기정화 식물 세트(샘플)",
      main_category: "식물/화분",
      mid_category: "공기정화",
      code: "SAMPLE-PLANT-AIR",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "웨딩 부케 라운드(샘플)",
      main_category: "웨딩상품",
      mid_category: "부케",
      code: "SAMPLE-WEDDING-BOUQUET",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "센터피스 테이블(샘플)",
      main_category: "플라워",
      mid_category: "센터피스",
      code: "SAMPLE-CENTERPIECE",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "플랜트 중품 몬스테라(샘플)",
      main_category: "플랜트",
      mid_category: "중품",
      code: "SAMPLE-PLANT-MID",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "유리 화병 세트(샘플)",
      main_category: "화병/화기",
      mid_category: "유리병",
      code: "SAMPLE-VASE-GLASS",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "리스 소형(샘플)",
      main_category: "기타",
      mid_category: "리스",
      code: "SAMPLE-WREATH-SM",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "꽃바구니 L 프리미엄(샘플)",
      main_category: "꽃바구니",
      mid_category: "L사이즈",
      code: "SAMPLE-BASKET-L",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "심비디움 분화(샘플)",
      main_category: "서양란",
      mid_category: "심비디움",
      code: "SAMPLE-ORCHID-CYM",
      price: 0,
      stock: 0,
      status: "active",
    },
    {
      name: "다육 미니 세트(샘플)",
      main_category: "식물/화분",
      mid_category: "다육/선인장",
      code: "SAMPLE-SUCCULENT-SET",
      price: 0,
      stock: 0,
      status: "active",
    },
  ],
  materials: [
    { name: "오아시스 브릭(샘플)", main_category: "부자재", mid_category: "소품", unit: "개", spec: "표준" },
    { name: "이태리지 60cm(샘플)", main_category: "포장재", mid_category: "포장지", unit: "매", spec: "60cm" },
    { name: "아크릴 라운드 박스(샘플)", main_category: "부자재", mid_category: "화기", unit: "개", spec: "중" },
    { name: "장미 50cm 레드(샘플)", main_category: "생화", mid_category: "장미류", unit: "송이", spec: "50cm" },
    { name: "유칼립투스(샘플)", main_category: "생화", mid_category: "소재(그린)", unit: "단", spec: "" },
    { name: "거베라 혼합(샘플)", main_category: "생화", mid_category: "거베라류", unit: "송이", spec: "" },
    { name: "리시안서스 화이트(샘플)", main_category: "생화", mid_category: "리시안서스류", unit: "송이", spec: "" },
    { name: "튤립 옐로우(샘플)", main_category: "생화", mid_category: "튤립류", unit: "송이", spec: "" },
    { name: "스프레이 카네이션(샘플)", main_category: "생화", mid_category: "카네이션류", unit: "단", spec: "" },
    { name: "안개꽃(샘플)", main_category: "생화", mid_category: "절지류", unit: "단", spec: "" },
    { name: "선인장 소품(샘플)", main_category: "식물", mid_category: "선인장", unit: "개", spec: "" },
    { name: "관엽 소형(샘플)", main_category: "식물", mid_category: "관엽소품", unit: "개", spec: "" },
    { name: "서양란 화분(샘플)", main_category: "식물", mid_category: "서양란", unit: "개", spec: "" },
    { name: "유리 화기 직경12(샘플)", main_category: "부자재", mid_category: "유리", unit: "개", spec: "12cm" },
    { name: "도자기 화분(샘플)", main_category: "부자재", mid_category: "도자기", unit: "개", spec: "" },
    { name: "쉬폰 포장지(샘플)", main_category: "포장재", mid_category: "포장지", unit: "매", spec: "" },
    { name: "골지 리본 2.5cm(샘플)", main_category: "리본", mid_category: "리본(폭좁음)", unit: "롤", spec: "2.5cm" },
    { name: "와이어·테이프 세트(샘플)", main_category: "부자재", mid_category: "소품", unit: "세트", spec: "" },
    { name: "비닐 포장지(샘플)", main_category: "포장재", mid_category: "비닐", unit: "매", spec: "" },
    { name: "조화 잎사귀(샘플)", main_category: "부자재", mid_category: "조화", unit: "단", spec: "" },
  ],
};
