/**
 * Electron SyncWorker 트래픽·속도 균형 (ERP lilymagerp-v4_supa 동일)
 */
module.exports = {
  SYNC_INTERVAL_ACTIVE_MS: 10_000,
  SYNC_INTERVAL_IDLE_MS: 30_000,
  IDLE_THRESHOLD_MS: 120_000,
  DELETED_SYNC_ORDERS_EVERY_N: 18,
  DELETED_SYNC_CUSTOMERS_EVERY_N: 54,
  IMMEDIATE_SYNC_DEBOUNCE_MS: 400,
};
