"use client";
import { useState, useEffect, useCallback } from 'react';
import { createClient } from '@/utils/supabase/client';
import { useAuth } from '@/hooks/use-auth';
import { toast } from "sonner";
import { deleteById, deleteRows, isDeleteNoRows } from "@/lib/supabase/delete-by-id";
const supabase = createClient();
import { useMaterials } from '@/hooks/use-materials';
import { useProducts } from '@/hooks/use-products';
import type {
  SimpleExpense,
  CreateSimpleExpenseData,
  FixedCostTemplate,
  SupplierSuggestion,
  ExpenseStats
} from '@/types/simple-expense';
import { SimpleExpenseCategory } from '@/types/simple-expense';
import { isElectronClient } from '@/lib/electron-env';
import { onElectronSyncStatus } from '@/lib/electron-sync-listener';
import { uploadWithOptimalStorage } from '@/lib/storage-manager';

interface MaterialRequest {
  id: string;
  branchId?: string;
  tenantName?: string;
  requestNumber?: string;
  [key: string]: any;
}

export function useSimpleExpenses({ enableRealtime = false }: { enableRealtime?: boolean } = {}) {
  const [expenses, setExpenses] = useState<SimpleExpense[]>([]);
  const [loading, setLoading] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [supplierSuggestions, setSupplierSuggestions] = useState<SupplierSuggestion[]>([]);
  const { user } = useAuth();
  const { materials } = useMaterials(); const updateMaterialStock = async (_items: any[], _dir?: string, _tenant?: string, _user?: string) => {}; const generateNewId = (_mainCat?: string, _midCat?: string, _tenant?: string) => "new-id";
  const { products } = useProducts(); const updateProductStock = async (_items: any[], _dir?: string, _tenant?: string, _user?: string) => {};

  const mapRowToExpense = useCallback((row: any): SimpleExpense => ({
    id: row.id,
    date: row.expense_date,
    amount: Number(row.amount),
    category: row.category,
    subCategory: row.sub_category,
    description: row.description,
    supplier: row.supplier,
    quantity: row.quantity,
    unitPrice: Number(row.unit_price),
    branchId: row.tenant_id,
    tenantName: row.tenant_name,
    paymentMethod: row.payment_method || row.extra_data?.payment_method,
    receiptUrl: row.receipt_url,
    receiptFileName: row.receipt_file_name,
    inventoryUpdates: row.inventory_updates || [],
    relatedRequestId: row.related_request_id || row.extra_data?.related_request_id,
    relatedOrderId: row.related_order_id || row.extra_data?.related_order_id,
    isAutoGenerated: row.is_auto_generated,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  }), []);

  const fetchExpenses = useCallback(async (filters?: {
    branchId?: string;
    category?: SimpleExpenseCategory;
    dateFrom?: Date;
    dateTo?: Date;
    limit?: number;
    offset?: number;
  }) => {
    if (!user) return;

    // Smart loading: only show full skeleton on first load or when changing filters significantly
    const isFirstLoad = !filters?.offset;

    // We use a functional update for setExpenses to avoid dependency on 'expenses' state
    if (isFirstLoad) {
      // Instead of checking expenses.length (which creates a dependency loop),
      // we check the state using a setter or just use isRefreshing if not offset.
      setIsRefreshing(true);
    }

    try {
      let query = supabase.from('simple_expenses').select('*');
      if (filters?.branchId) query = query.eq('tenant_id', filters.branchId);
      if (filters?.category) query = query.eq('category', filters.category);
      if (filters?.dateFrom) query = query.gte('expense_date', filters.dateFrom.toISOString());
      if (filters?.dateTo) query = query.lte('expense_date', filters.dateTo.toISOString());

      const limit = filters?.limit || 10000;
      const offset = filters?.offset || 0;

      const { data, error } = await query
        .order('expense_date', { ascending: false })
        .range(offset, offset + limit - 1);

      if (error) throw error;
      const expenseList = (data || []).map(mapRowToExpense);

      if (offset > 0) {
        setExpenses(prev => [...prev, ...expenseList]);
      } else {
        setExpenses(expenseList);
      }

      return { expenses: expenseList, hasMore: expenseList.length >= limit };
    } catch (error: any) {
      console.error(error);
      if (error?.code === 'PGRST301' || error?.status === 401 || error?.message?.includes('JWT')) {
        supabase.auth.signOut();
      }
      toast.error("지출 목록 로드 실패");
      return { expenses: [] as SimpleExpense[], hasMore: false };
    } finally {
      if (isFirstLoad) {
        setLoading(false);
      }
      setIsRefreshing(false);
    }
  }, [user, toast, mapRowToExpense]); // Stable dependencies

  const addExpense = useCallback(async (data: CreateSimpleExpenseData, branchId: string, tenantName: string): Promise<boolean> => {
    if (!user) return false;
    setLoading(true);
    try {
      let receiptUrl = '';
      let receiptFileName = '';
      if (data.receiptFile) {
        const path = `${branchId}/${Date.now()}_${data.receiptFile.name.replace(/\.[^/.]+$/, "")}.jpg`;
        const uploadResult = await uploadWithOptimalStorage(data.receiptFile, path, {
          bucket: "receipts",
        });
        receiptUrl = uploadResult.url;
        receiptFileName = data.receiptFile.name;
      }

      const id = crypto.randomUUID();
      const payload = {
        id,
        expense_date: data.date instanceof Date ? data.date.toISOString() : data.date,
        amount: data.amount,
        category: data.category,
        sub_category: data.subCategory, // Using camelCase subCategory as verified above
        description: data.description,
        supplier: data.supplier,
        quantity: data.quantity || 1,
        unit_price: data.unitPrice || 0,
        tenant_id: branchId,
        tenant_name: tenantName,
        // payment_method removed from top level if column missing, add to extra_data
        receipt_url: receiptUrl,
        receipt_file_name: receiptFileName,
        inventory_updates: data.inventoryUpdates || [],
        // related_request_id: data.relatedRequestId,
        // related_order_id: data.relatedOrderId, // Removed to fix 400 error
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        extra_data: {
          payment_method: data.paymentMethod,
          related_order_id: data.relatedOrderId,
          related_request_id: data.relatedRequestId
        }
      };

      const { error } = await supabase.from('simple_expenses').insert([payload]);
      if (error) throw error;

      // Sync Partner
      if (data.supplier) {
        const { data: partner } = await supabase.from('partners').select('*').eq('name', data.supplier).maybeSingle();
        if (!partner) {
          await supabase.from('partners').insert([{
            id: crypto.randomUUID(), name: data.supplier, type: '기타공급업체', branch: tenantName, memo: `간편지출 자동 추가`, created_at: new Date().toISOString()
          }]);
        }
      }

      // Sync Material
      let materialUpdatedId = null;
      if (data.category === SimpleExpenseCategory.MATERIAL && data.description) {
        const { data: mat } = await supabase.from('materials').select('*').eq('name', data.description).eq('branch', tenantName).maybeSingle();
        let mainCategory = '기타자재';
        if (data.subCategory === 'fresh_flower' || data.subCategory === '생화') mainCategory = '생화';
        else if (data.subCategory === 'artificial_flower' || data.subCategory === '조화') mainCategory = '조화';
        else if (data.subCategory === 'preserved' || data.subCategory === '프리저브드') mainCategory = '프리저브드';
        else if (data.subCategory === 'plant' || data.subCategory === '식물') mainCategory = '식물';
        else if (data.subCategory === 'container' || data.subCategory === '바구니 / 화기') mainCategory = '바구니 / 화기';
        else if (data.subCategory === 'supply' || data.subCategory === '소모품 및 부자재') mainCategory = '소모품 및 부자재';

        if (!mat) {
          const newId = await generateNewId(mainCategory, data.materialMidCategory || '기타', tenantName);
          materialUpdatedId = newId;
          await supabase.from('materials').insert([{
            id: newId,
            name: data.description,
            main_category: mainCategory,
            mid_category: data.materialMidCategory || '기타',
            price: data.unitPrice || 0,
            supplier: data.supplier || '미지정',
            stock: 0,
            branch: tenantName,
            created_at: new Date().toISOString()
          }]);

          await updateMaterialStock([{
            id: newId,
            name: data.description,
            quantity: data.quantity || 1,
            price: data.unitPrice || 0,
            supplier: data.supplier
          }], 'in', tenantName, user.email || 'system');
        } else {
          materialUpdatedId = mat.id;
          await updateMaterialStock([{
            id: mat.id,
            name: mat.name,
            quantity: data.quantity || 1,
            price: data.unitPrice || mat.price,
            supplier: data.supplier || mat.supplier
          }], 'in', tenantName, user.email || 'system');
        }
      }

      // Sync Stock (from inventoryUpdates)
      if (data.inventoryUpdates?.length) {
        for (const item of data.inventoryUpdates) {
          // avoid double-counting if we already updated it in the Sync Material block
          if (item.type === 'material' && item.id !== materialUpdatedId) {
            await updateMaterialStock([{ id: item.id, name: item.name, quantity: item.quantity, price: item.unitPrice }], 'in', tenantName, user.email || 'system');
          } else if (item.type === 'product') {
            await updateProductStock([{ id: item.id, name: item.name, quantity: item.quantity, price: item.unitPrice }], 'in', tenantName, user.email || 'system');
          }
        }
      }

      // Sync Material Request
      if (data.relatedRequestId) {
        await supabase.from('material_requests').update({ status: 'completed', updated_at: new Date().toISOString() }).eq('id', data.relatedRequestId);
      }

      // Sync Supplier Suggestions
      if (data.supplier) {
        const { data: sugg } = await supabase.from('supplier_suggestions').select('*').eq('name', data.supplier).maybeSingle();
        if (!sugg) await supabase.from('supplier_suggestions').insert([{ id: crypto.randomUUID(), name: data.supplier, category: data.category, frequency: 1, last_used: new Date().toISOString() }]);
        else await supabase.from('supplier_suggestions').update({ frequency: (sugg.frequency || 0) + 1, last_used: new Date().toISOString() }).eq('id', sugg.id);
      }

      toast.success("지출이 등록되었습니다.");
      await fetchExpenses();
      return true;
    } catch (error) {
      console.error(error);
      toast.error("지출 등록 실패");
      return false;
    } finally {
      setLoading(false);
    }
  }, [user, toast, updateMaterialStock, updateProductStock, fetchExpenses]);

  const updateExpense = useCallback(async (expenseId: string, data: Partial<CreateSimpleExpenseData>): Promise<boolean> => {
    if (!user) return false;
    setLoading(true);
    try {
      const updatePayload: Record<string, unknown> = { updated_at: new Date().toISOString() };
      if (data.receiptUrl === null) {
        updatePayload.receipt_url = null;
        updatePayload.receipt_file_name = null;
      }
      if (data.receiptFile) {
        const { data: exp } = await supabase.from('simple_expenses').select('tenant_id').eq('id', expenseId).single();
        if (exp) {
          const path = `${exp.tenant_id}/${Date.now()}_${data.receiptFile.name.replace(/\.[^/.]+$/, "")}.jpg`;
          const uploadResult = await uploadWithOptimalStorage(data.receiptFile, path, { bucket: "receipts" });
          updatePayload.receipt_url = uploadResult.url;
          updatePayload.receipt_file_name = data.receiptFile.name;
        }
      }
      if (data.amount) updatePayload.amount = data.amount;
      if (data.description) updatePayload.description = data.description;
      if (data.date) updatePayload.expense_date = data.date instanceof Date ? data.date.toISOString() : data.date;

      const { error } = await supabase.from('simple_expenses').update(updatePayload).eq('id', expenseId);
      if (error) throw error;
      toast.success("지출 정보가 수정되었습니다.");
      await fetchExpenses();
      return true;
    } catch (error) {
      console.error(error);
      return false;
    } finally {
      setLoading(false);
    }
  }, [user, fetchExpenses]);

  const updateExpenseByOrderId = useCallback(async (orderId: string, data: Partial<CreateSimpleExpenseData>, matchSubCategory?: string): Promise<boolean> => {
    if (!user) return false;
    try {
      // 'related_order_id' column doesn't exist, check extra_data using contains
      // .eq('extra_data->>related_order_id', orderId) can be unstable depending on driver version
      let query = supabase.from('simple_expenses').select('id')
        .contains('extra_data', { related_order_id: orderId });

      if (matchSubCategory) {
        query = query.eq('sub_category', matchSubCategory);
      }

      const { data: existing } = await query.maybeSingle();

      if (!existing) return false;

      const updatePayload: any = { updated_at: new Date().toISOString() };
      if (data.amount) updatePayload.amount = data.amount;
      if (data.description) updatePayload.description = data.description;
      if (data.supplier) updatePayload.supplier = data.supplier;
      if (data.date) updatePayload.expense_date = data.date instanceof Date ? data.date.toISOString() : data.date;

      // 'payment_method' column missing, store in extra_data
      if (data.paymentMethod) {
        // We need to fetch current extra_data or merge carefully. 
        // Ideally we fetch it first, but for now assuming we can merge via jsonb update or fetch existing.
        // Actually, Postgrest update generally replaces columns. For JSONB columns to deep merge, we might need a stored procedure or fetch-modify-save.
        // But here let's fetch current extra_data.
        const { data: current } = await supabase.from('simple_expenses').select('extra_data').eq('id', existing.id).single();
        updatePayload.extra_data = {
          ...(current?.extra_data || {}),
          payment_method: data.paymentMethod
        };
      }

      const { error } = await supabase.from('simple_expenses').update(updatePayload).eq('id', existing.id);
      if (error) throw error;
      await fetchExpenses();
      return true;
    } catch (error) {
      console.error('지출 업데이트 오류:', error);
      return false;
    }
  }, [user, fetchExpenses]);

  const deleteExpense = useCallback(async (expenseId: string): Promise<boolean> => {
    if (!user) return false;
    try {
      const result = await deleteById(supabase, 'simple_expenses', expenseId);
      if (result.error) throw result.error;
      if (isDeleteNoRows(result)) return false;
      toast.success("성공했습니다.");
      await fetchExpenses();
      return true;
    } catch (error) {
      console.error(error);
      return false;
    }
  }, [user, fetchExpenses]);

  const deleteExpenseByOrderId = useCallback(async (orderId: string, matchSubCategory?: string): Promise<boolean> => {
    if (!user) return false;
    try {
      // 'related_order_id' column doesn't exist, check extra_data->>related_order_id
      // 'related_order_id' column doesn't exist, check extra_data using contains
      let query = supabase.from('simple_expenses').delete({ count: 'exact' })
        .contains('extra_data', { related_order_id: orderId });

      if (matchSubCategory) {
        query = query.eq('sub_category', matchSubCategory);
      }

      const { error, count } = await query;
      if (error) throw error;
      if (!count) return false;
      await fetchExpenses();
      return true;
    } catch (error) {
      console.error('지출 삭제 오류:', error);
      return false;
    }
  }, [user, fetchExpenses]);

  const fetchSupplierSuggestions = useCallback(async (searchTerm: string = '') => {
    try {
      let query = supabase.from('supplier_suggestions').select('*').order('frequency', { ascending: false }).limit(10);
      if (searchTerm) query = query.ilike('name', `%${searchTerm}%`);
      const { data } = await query;
      setSupplierSuggestions((data || []).map(s => ({ id: s.id, name: s.name, category: s.category, frequency: s.frequency, lastUsed: s.last_used })));
    } catch (error) { console.error(error); }
  }, []);

  const fetchFixedCostTemplate = useCallback(async (branchId: string): Promise<FixedCostTemplate | null> => {
    try {
      const { data } = await supabase.from('fixed_cost_templates').select('*').eq('tenant_id', branchId).maybeSingle();
      if (!data) return null;
      return { id: data.id, branchId: data.tenant_id, tenantName: data.tenant_name, items: data.items, createdAt: data.created_at, updatedAt: data.updated_at };
    } catch (error) { return null; }
  }, []);

  const saveFixedCostTemplate = useCallback(async (branchId: string, tenantName: string, items: any[]): Promise<boolean> => {
    if (!user) return false;
    try {
      const existing = await fetchFixedCostTemplate(branchId);
      const payload = { tenant_id: branchId, tenant_name: tenantName, items, updated_at: new Date().toISOString() };
      if (existing) await supabase.from('fixed_cost_templates').update(payload).eq('id', existing.id);
      else await supabase.from('fixed_cost_templates').insert([{ ...payload, id: crypto.randomUUID(), created_at: new Date().toISOString() }]);
      toast.success("템플릿이 저장되었습니다.");
      return true;
    } catch (error) { return false; }
  }, [user, fetchFixedCostTemplate]);

  const addFixedCosts = useCallback(async (branchId: string, tenantName: string, items: any[], date: Date): Promise<boolean> => {
    if (!user) return false;
    setLoading(true);
    try {
      const activeItems = items.filter(item => item.isActive && item.amount > 0);
      const payloads = activeItems.map(item => ({
        id: crypto.randomUUID(),
        expense_date: date.toISOString(),
        amount: item.amount,
        category: item.category,
        sub_category: item.subCategory,
        description: item.name,
        supplier: item.supplier,
        tenant_id: branchId,
        tenant_name: tenantName,
        extra_data: {
          from_fixed_template: true,
          due_day: item.dueDay ?? null,
        },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      }));
      const { error } = await supabase.from('simple_expenses').insert(payloads);
      if (error) throw error;
      toast.success("일괄 입력 완료", { description: `${payloads.length}개 지출 등록됨` });
      await fetchExpenses();
      return true;
    } catch (error) { return false; } finally { setLoading(false); }
  }, [user, fetchExpenses]);

  const calculateStats = useCallback((expenseList: SimpleExpense[]): ExpenseStats => {
    const totalAmount = expenseList.reduce((sum, expense) => sum + expense.amount, 0);
    const categoryMap = new Map();
    expenseList.forEach(expense => {
      const existing = categoryMap.get(expense.category) || { amount: 0, count: 0 };
      categoryMap.set(expense.category, { amount: existing.amount + expense.amount, count: existing.count + 1 });
    });
    const categoryBreakdown = Array.from(categoryMap.entries()).map(([category, data]) => ({ category, amount: data.amount, count: data.count, percentage: totalAmount > 0 ? (data.amount / totalAmount) * 100 : 0 }));

    const monthlyMap = new Map();
    expenseList.forEach(expense => {
      const monthKey = new Date(expense.date).toISOString().slice(0, 7);
      monthlyMap.set(monthKey, (monthlyMap.get(monthKey) || 0) + expense.amount);
    });
    const monthlyTrend = Array.from(monthlyMap.entries()).sort(([a], [b]) => a.localeCompare(b)).slice(-6).map(([month, amount]) => ({ month, amount }));

    const supplierMap = new Map();
    expenseList.forEach(expense => {
      const existing = supplierMap.get(expense.supplier) || { amount: 0, count: 0 };
      supplierMap.set(expense.supplier, { amount: existing.amount + expense.amount, count: existing.count + 1 });
    });
    const topSuppliers = Array.from(supplierMap.entries()).map(([name, data]) => ({ name, amount: data.amount, count: data.count })).sort((a, b) => b.amount - a.amount).slice(0, 10);

    return { totalAmount, categoryBreakdown, monthlyTrend, topSuppliers };
  }, []);

  const addMaterialRequestExpense = useCallback(async (materialRequest: MaterialRequest, actualPurchaseInfo: any): Promise<boolean> => {
    if (!actualPurchaseInfo || !materialRequest.branchId) return false;
    try {
      const purchaseItems = actualPurchaseInfo.items || [];
      const supplierName = purchaseItems[0]?.supplier || '자재구매';

      // 각 품목별로 별도의 지출 내역을 생성하여 리스트에 각각 표시되도록 함
      // 사용자가 품목별 단가와 수량을 지출 내역에서 바로 확인할 수 있도록 개선
      const payloads = purchaseItems.map((item: any) => ({
        id: crypto.randomUUID(),
        expense_date: actualPurchaseInfo.purchaseDate,
        amount: (item.quantity || 1) * (item.unitPrice || 0),
        category: SimpleExpenseCategory.MATERIAL,
        sub_category: 'material_request',
        description: `[${materialRequest.requestNumber}] ${item.name.trim()}`,
        supplier: item.supplier || supplierName,
        quantity: item.quantity || 1,
        unit_price: item.unitPrice || 0,
        tenant_id: materialRequest.branchId,
        tenant_name: materialRequest.tenantName,
        related_request_id: materialRequest.id,
        is_auto_generated: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        extra_data: {
          related_request_id: materialRequest.id,
          request_number: materialRequest.requestNumber,
          item_name: item.name,
          quantity: item.quantity,
          unit_price: item.unitPrice,
          supplier: item.supplier || supplierName
        }
      }));

      const { error } = await supabase.from('simple_expenses').insert(payloads);
      if (error) throw error;

      toast.success('성공', { description: `${supplierName} - 총 ${purchaseItems.length}건의 품목별 지출이 등록되었습니다.` });
      return true;
    } catch (error) {
      console.error('자재요청 지출 등록 오류:', error);
      return false;
    }
  }, [toast]);

  // 자재요청 ID로 자동 생성된 지출 삭제 (배송완료 취소 시 사용)
  const deleteExpenseByRequestId = useCallback(async (requestId: string): Promise<boolean> => {
    try {
      const result = await deleteRows(supabase, 'simple_expenses', {
        related_request_id: requestId,
      });
      if (result.error) throw result.error;
      return result.ok;
    } catch (error) {
      console.error('자재요청 지출 삭제 오류:', error);
      return false;
    }
  }, []);

  useEffect(() => {
    if (user) {
      if (enableRealtime) {
        fetchExpenses();
      }
      fetchSupplierSuggestions();
    }

    if (!enableRealtime || !user) return;

    if (isElectronClient()) {
      let lastAt: string | null = null;
      const unsub = onElectronSyncStatus((status) => {
        if (!status.lastSyncAt || status.lastSyncAt === lastAt) return;
        lastAt = status.lastSyncAt;
        fetchExpenses();
      });
      return () => unsub();
    }

    // Real-time synchronization
    const channelName = `simple-expenses-realtime-${crypto.randomUUID()}`;
    const channel = supabase
      .channel(channelName)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'simple_expenses' }, () => {
        fetchExpenses();
      })
      .subscribe();

    return () => {
      if (channel) {
        setTimeout(() => {
          try {
            supabase.removeChannel(channel).catch(() => { });
          } catch (e) { }
        }, 0);
      }
    };
  }, [user, fetchExpenses, fetchSupplierSuggestions, enableRealtime]);

  return {
    expenses, loading, supplierSuggestions, isRefreshing,
    fetchExpenses, addExpense, updateExpense, deleteExpense,
    updateExpenseByOrderId, deleteExpenseByOrderId,
    fetchSupplierSuggestions, fetchFixedCostTemplate, saveFixedCostTemplate, addFixedCosts, calculateStats, addMaterialRequestExpense, deleteExpenseByRequestId
  };
}
