// 간단한 지출 카테고리 - 꽃집 사업에 최적화
export enum SimpleExpenseCategory {
  MATERIAL = 'material',        // 자재비 (꽃, 화분, 포장재 등)
  FIXED_COST = 'fixed_cost',   // 고정비 (임대료, 관리비, 주차료)
  UTILITY = 'utility',         // 공과금 (전기, 가스, 수도, 인터넷)
  TRANSPORT = 'transport',     // 운송비 (배송료, 택시비, 주유비)
  OFFICE = 'office',          // 사무용품 (문구류, 청소용품, 사무기기)
  MARKETING = 'marketing',     // 마케팅비 (광고, 홍보물, 이벤트)
  MEAL = 'meal',              // 식비 (직원식대, 회식)
  MAINTENANCE = 'maintenance', // 유지보수비 (설비, 정비)
  INSURANCE = 'insurance',     // 보험료 (사업자보험, 배송보험)
  OTHER = 'other'             // 기타
}
// 자재비 세부 분류 - 자재요청 카테고리와 통일
export enum MaterialSubCategory {
  FRESH_FLOWER = 'fresh_flower',      // 생화
  ARTIFICIAL_FLOWER = 'artificial_flower', // 조화
  PRESERVED = 'preserved',            // 프리저브드
  PLANT = 'plant',                    // 식물
  CONTAINER = 'container',            // 바구니 / 화기
  SUPPLY = 'supply',                  // 소모품 및 부자재
  OUTSOURCE = 'outsource',            // 외부발주
  MATERIAL_REQUEST = 'material_request' // 자재요청
}
// 고정비 세부 분류
export enum FixedCostSubCategory {
  RENT = 'rent',           // 임대료
  MANAGEMENT = 'management', // 관리비
  PARKING = 'parking',     // 주차료
  SECURITY = 'security',   // 보안료
  LABOR = 'labor',         // 인건비
  LICENSE = 'license'      // 사업자등록세, 각종 허가료
}
// 공과금 세부 분류
export enum UtilitySubCategory {
  ELECTRICITY = 'electricity', // 전기료
  GAS = 'gas',                // 가스료
  WATER = 'water',            // 수도료
  INTERNET = 'internet',      // 인터넷료
  PHONE = 'phone',            // 전화료
  WASTE = 'waste'             // 폐기물 처리비
}
// 운송비 세부 분류
export enum TransportSubCategory {
  DELIVERY = 'delivery',       // 배송료
  TAXI = 'taxi',              // 택시비
  FUEL = 'fuel',              // 주유비
  PARKING_FEE = 'parking_fee', // 주차비
  TOLL = 'toll'               // 통행료
}
// 사무용품 세부 분류
export enum OfficeSubCategory {
  STATIONERY = 'stationery',   // 문구류
  CLEANING = 'cleaning',       // 청소용품
  EQUIPMENT = 'equipment',     // 사무기기
  SUPPLY = 'supply'           // 소모품
}
// 마케팅비 세부 분류
export enum MarketingSubCategory {
  ADVERTISING = 'advertising', // 광고비
  PROMOTION = 'promotion',     // 홍보물
  EVENT = 'event',            // 이벤트비
  SNS = 'sns',                // SNS 마케팅
  PRINTING = 'printing'       // 인쇄비
}
// 유지보수비 세부 분류
export enum MaintenanceSubCategory {
  EQUIPMENT = 'equipment',     // 설비정비
  AIR_CONDITIONING = 'air_conditioning', // 에어컨정비
  REFRIGERATOR = 'refrigerator', // 냉장고정비
  PLUMBING = 'plumbing',      // 배관정비
  ELECTRICAL = 'electrical'   // 전기정비
}
// 보험료 세부 분류
export enum InsuranceSubCategory {
  BUSINESS = 'business',       // 사업자보험
  DELIVERY = 'delivery',       // 배송보험
  LIABILITY = 'liability',     // 책임보험
  PROPERTY = 'property',       // 재산보험
  // 4대보험 관련
  NATIONAL_PENSION = 'national_pension',     // 국민연금
  HEALTH_INSURANCE = 'health_insurance',     // 건강보험
  EMPLOYMENT_INSURANCE = 'employment_insurance', // 고용보험
  INDUSTRIAL_ACCIDENT = 'industrial_accident' // 산재보험
}
// 식비 세부 분류
export enum MealSubCategory {
  GENERAL = 'general',         // 일반식비
  COMPANY_DINNER = 'company_dinner', // 회식비
  SPECIAL = 'special',         // 특별식비
  COFFEE = 'coffee'           // 커피, 음료
}
// 재고 업데이트 아이템 인터페이스
export interface InventoryUpdateItem {
  type: 'material' | 'product';
  id: string;
  name: string;
  quantity: number;
  unitPrice?: number;
}
// 간단한 지출 기록 인터페이스
export interface SimpleExpense {
  id: string;
  date: any; // string (ISO) or Date
  amount: number;
  category: SimpleExpenseCategory;
  subCategory?: string;
  description: string;
  supplier: string;
  quantity?: number;
  unitPrice?: number;
  paymentMethod?: 'card' | 'cash' | 'transfer' | 'other';
  receiptUrl?: string;
  receiptFileName?: string;
  branchId: string;
  tenantName: string;
  relatedRequestId?: string;
  relatedOrderId?: string;
  isAutoGenerated?: boolean;
  inventoryUpdates?: InventoryUpdateItem[];
  createdAt: any;
  updatedAt: any;
}
// 고정비 템플릿 인터페이스
export interface FixedCostTemplate {
  id: string;
  branchId: string;
  tenantName: string;
  // 템플릿 항목들
  items: FixedCostItem[];
  // 메타데이터
  createdAt: any;
  updatedAt: any;
}
export interface FixedCostItem {
  id: string;
  name: string;
  category: SimpleExpenseCategory;
  subCategory: string; // Allow any subcategory string instead of FixedCostSubCategory
  amount: number;
  supplier: string;
  isActive: boolean;
  dueDay?: number; // 매월 결제일 (1-31)
}
// 지출 입력 데이터
export interface CreateSimpleExpenseData {
  date: any;
  amount: number;
  category: SimpleExpenseCategory;
  subCategory?: string;
  description: string;
  supplier: string;
  quantity?: number;
  unitPrice?: number;
  paymentMethod?: 'card' | 'cash' | 'transfer' | 'other';
  receiptFile?: File;
  inventoryUpdates?: InventoryUpdateItem[];
  relatedRequestId?: string;
  relatedOrderId?: string;
  materialMidCategory?: string;
}
// 구매처 자동완성 데이터
export interface SupplierSuggestion {
  id?: string;
  name: string;
  category: SimpleExpenseCategory;
  frequency: number;
  lastUsed: any;
}
// 지출 통계 데이터
export interface ExpenseStats {
  totalAmount: number;
  categoryBreakdown: {
    category: SimpleExpenseCategory;
    amount: number;
    count: number;
    percentage: number;
  }[];
  monthlyTrend: {
    month: string;
    amount: number;
  }[];
  topSuppliers: {
    name: string;
    amount: number;
    count: number;
  }[];
}
// 지점별 지출 요약
export interface BranchExpenseSummary {
  branchId: string;
  tenantName: string;
  totalAmount: number;
  categoryBreakdown: {
    category: SimpleExpenseCategory;
    amount: number;
  }[];
  lastUpdated: any;
}
// 민감한 세부 분류 (본사 관리자만 접근 가능)
export const SENSITIVE_SUBCATEGORIES: Partial<Record<SimpleExpenseCategory, string[]>> = {
  [SimpleExpenseCategory.FIXED_COST]: [
    FixedCostSubCategory.LABOR, // 인건비
  ],
  [SimpleExpenseCategory.INSURANCE]: [
    InsuranceSubCategory.NATIONAL_PENSION,     // 국민연금
    InsuranceSubCategory.HEALTH_INSURANCE,     // 건강보험
    InsuranceSubCategory.EMPLOYMENT_INSURANCE, // 고용보험
    InsuranceSubCategory.INDUSTRIAL_ACCIDENT,  // 산재보험
  ]
};

// 민감한 세부 분류 접근 권한 체크 함수
export const canViewSubCategory = (category: SimpleExpenseCategory, subCategory: string, userRole: string): boolean => {
  const sensitiveSubs = SENSITIVE_SUBCATEGORIES[category] || [];
  const isSensitive = sensitiveSubs.includes(subCategory as any);
  return !isSensitive || userRole === 'head_office_admin' || userRole === 'hq_manager';
};

// 민감한 세부 분류인지 확인하는 함수
export const isSensitiveSubCategory = (category: SimpleExpenseCategory, subCategory: string): boolean => {
  const sensitiveSubs = SENSITIVE_SUBCATEGORIES[category] || [];
  return sensitiveSubs.includes(subCategory as any);
};

// 라벨 매핑
export const SIMPLE_EXPENSE_CATEGORY_LABELS: Record<SimpleExpenseCategory, string> = {
  [SimpleExpenseCategory.MATERIAL]: '자재비',
  [SimpleExpenseCategory.FIXED_COST]: '고정비',
  [SimpleExpenseCategory.UTILITY]: '공과금',
  [SimpleExpenseCategory.TRANSPORT]: '운송비',
  [SimpleExpenseCategory.OFFICE]: '사무용품',
  [SimpleExpenseCategory.MARKETING]: '마케팅비',
  [SimpleExpenseCategory.MEAL]: '식비',
  [SimpleExpenseCategory.MAINTENANCE]: '유지보수비',
  [SimpleExpenseCategory.INSURANCE]: '보험료',
  [SimpleExpenseCategory.OTHER]: '기타'
};
export const MEAL_SUB_CATEGORY_LABELS: Record<MealSubCategory, string> = {
  [MealSubCategory.GENERAL]: '일반식비',
  [MealSubCategory.COMPANY_DINNER]: '회식비',
  [MealSubCategory.SPECIAL]: '특별식비',
  [MealSubCategory.COFFEE]: '커피/음료'
};
export const FIXED_COST_SUB_CATEGORY_LABELS: Record<FixedCostSubCategory, string> = {
  [FixedCostSubCategory.RENT]: '임대료',
  [FixedCostSubCategory.MANAGEMENT]: '관리비',
  [FixedCostSubCategory.PARKING]: '주차료',
  [FixedCostSubCategory.SECURITY]: '보안료',
  [FixedCostSubCategory.LABOR]: '인건비',
  [FixedCostSubCategory.LICENSE]: '사업자등록세/허가료'
};
export const MATERIAL_SUB_CATEGORY_LABELS: Record<MaterialSubCategory, string> = {
  [MaterialSubCategory.FRESH_FLOWER]: '생화',
  [MaterialSubCategory.ARTIFICIAL_FLOWER]: '조화',
  [MaterialSubCategory.PRESERVED]: '프리저브드',
  [MaterialSubCategory.PLANT]: '식물',
  [MaterialSubCategory.CONTAINER]: '바구니 / 화기',
  [MaterialSubCategory.SUPPLY]: '소모품 및 부자재',
  [MaterialSubCategory.OUTSOURCE]: '외부발주',
  [MaterialSubCategory.MATERIAL_REQUEST]: '자재요청'
};
export const UTILITY_SUB_CATEGORY_LABELS: Record<UtilitySubCategory, string> = {
  [UtilitySubCategory.ELECTRICITY]: '전기료',
  [UtilitySubCategory.GAS]: '가스료',
  [UtilitySubCategory.WATER]: '수도료',
  [UtilitySubCategory.INTERNET]: '인터넷료',
  [UtilitySubCategory.PHONE]: '전화료',
  [UtilitySubCategory.WASTE]: '폐기물처리비'
};
export const TRANSPORT_SUB_CATEGORY_LABELS: Record<TransportSubCategory, string> = {
  [TransportSubCategory.DELIVERY]: '배송료',
  [TransportSubCategory.TAXI]: '택시비',
  [TransportSubCategory.FUEL]: '주유비',
  [TransportSubCategory.PARKING_FEE]: '주차비',
  [TransportSubCategory.TOLL]: '통행료'
};
export const OFFICE_SUB_CATEGORY_LABELS: Record<OfficeSubCategory, string> = {
  [OfficeSubCategory.STATIONERY]: '문구류',
  [OfficeSubCategory.CLEANING]: '청소용품',
  [OfficeSubCategory.EQUIPMENT]: '사무기기',
  [OfficeSubCategory.SUPPLY]: '소모품'
};
export const MARKETING_SUB_CATEGORY_LABELS: Record<MarketingSubCategory, string> = {
  [MarketingSubCategory.ADVERTISING]: '광고비',
  [MarketingSubCategory.PROMOTION]: '홍보물',
  [MarketingSubCategory.EVENT]: '이벤트비',
  [MarketingSubCategory.SNS]: 'SNS마케팅',
  [MarketingSubCategory.PRINTING]: '인쇄비'
};
export const MAINTENANCE_SUB_CATEGORY_LABELS: Record<MaintenanceSubCategory, string> = {
  [MaintenanceSubCategory.EQUIPMENT]: '설비정비',
  [MaintenanceSubCategory.AIR_CONDITIONING]: '에어컨정비',
  [MaintenanceSubCategory.REFRIGERATOR]: '냉장고정비',
  [MaintenanceSubCategory.PLUMBING]: '배관정비',
  [MaintenanceSubCategory.ELECTRICAL]: '전기정비'
};
export const INSURANCE_SUB_CATEGORY_LABELS: Record<InsuranceSubCategory, string> = {
  [InsuranceSubCategory.BUSINESS]: '사업자보험',
  [InsuranceSubCategory.DELIVERY]: '배송보험',
  [InsuranceSubCategory.LIABILITY]: '책임보험',
  [InsuranceSubCategory.PROPERTY]: '재산보험',
  // 4대보험
  [InsuranceSubCategory.NATIONAL_PENSION]: '국민연금',
  [InsuranceSubCategory.HEALTH_INSURANCE]: '건강보험',
  [InsuranceSubCategory.EMPLOYMENT_INSURANCE]: '고용보험',
  [InsuranceSubCategory.INDUSTRIAL_ACCIDENT]: '산재보험'
};
export const generateExpenseId = (): string => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const time = String(now.getTime()).slice(-6);
  return `EXP-${year}${month}${day}-${time}`;
};
export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('ko-KR', {
    style: 'currency',
    currency: 'KRW'
  }).format(amount);
};
export const getCategoryColor = (category: SimpleExpenseCategory): string => {
  const colors: Record<SimpleExpenseCategory, string> = {
    [SimpleExpenseCategory.MATERIAL]: 'blue',
    [SimpleExpenseCategory.FIXED_COST]: 'purple',
    [SimpleExpenseCategory.UTILITY]: 'orange',
    [SimpleExpenseCategory.TRANSPORT]: 'green',
    [SimpleExpenseCategory.OFFICE]: 'indigo',
    [SimpleExpenseCategory.MARKETING]: 'pink',
    [SimpleExpenseCategory.MEAL]: 'yellow',
    [SimpleExpenseCategory.MAINTENANCE]: 'red',
    [SimpleExpenseCategory.INSURANCE]: 'cyan',
    [SimpleExpenseCategory.OTHER]: 'gray'
  };
  return colors[category];
};
// 기본 고정비 템플릿
export const DEFAULT_FIXED_COST_ITEMS: Omit<FixedCostItem, 'id'>[] = [
  {
    name: '임대료',
    category: SimpleExpenseCategory.FIXED_COST,
    subCategory: FixedCostSubCategory.RENT,
    amount: 1500000,
    supplier: '건물주',
    isActive: true,
    dueDay: 1
  },
  {
    name: '관리비',
    category: SimpleExpenseCategory.FIXED_COST,
    subCategory: FixedCostSubCategory.MANAGEMENT,
    amount: 200000,
    supplier: '관리사무소',
    isActive: true,
    dueDay: 5
  },
  {
    name: '주차료',
    category: SimpleExpenseCategory.FIXED_COST,
    subCategory: FixedCostSubCategory.PARKING,
    amount: 50000,
    supplier: '주차장',
    isActive: true,
    dueDay: 1
  },
  {
    name: '전기료',
    category: SimpleExpenseCategory.UTILITY,
    subCategory: UtilitySubCategory.ELECTRICITY,
    amount: 150000,
    supplier: '한국전력공사',
    isActive: true,
    dueDay: 15
  },
  {
    name: '가스료',
    category: SimpleExpenseCategory.UTILITY,
    subCategory: UtilitySubCategory.GAS,
    amount: 80000,
    supplier: '도시가스',
    isActive: true,
    dueDay: 20
  },
  {
    name: '인터넷료',
    category: SimpleExpenseCategory.UTILITY,
    subCategory: UtilitySubCategory.INTERNET,
    amount: 45000,
    supplier: 'KT',
    isActive: true,
    dueDay: 25
  }
];
