/** Billing period keys */
export type Period = "1m" | "3m" | "6m" | "12m";
export type PlanId = "free" | "erp_only" | "pro";

/** [ko, en, vi, ja, zh, es, pt, fr, de, ru] — `pickUiText`와 동일 순서 */
export type LocalizedString = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];

const L = (
  ko: string,
  en: string,
  vi: string,
  ja: string,
  zh: string,
  es: string,
  pt: string,
  fr: string,
  de: string,
  ru: string,
): LocalizedString => [ko, en, vi, ja, zh, es, pt, fr, de, ru];

const E = L("", "", "", "", "", "", "", "", "", "");

export const PERIOD_LABELS: Record<Period, LocalizedString> = {
  "1m": L("1개월", "1 month", "1 tháng", "1ヶ月", "1 个月", "1 mes", "1 mês", "1 mois", "1 Monat", "1 мес."),
  "3m": L("3개월", "3 months", "3 tháng", "3ヶ月", "3 个月", "3 meses", "3 meses", "3 mois", "3 Monate", "3 мес."),
  "6m": L("6개월", "6 months", "6 tháng", "6ヶ月", "6 个月", "6 meses", "6 meses", "6 mois", "6 Monate", "6 мес."),
  "12m": L("12개월", "12 months", "12 tháng", "12ヶ月", "12 个月", "12 meses", "12 meses", "12 mois", "12 Monate", "12 мес."),
};

export const PLAN_DISCOUNTS: Record<PlanId, Record<Period, LocalizedString>> = {
  free: {
    "1m": E,
    "3m": L("5% 할인", "5% off", "Giảm 5%", "5%オフ", "减 5%", "5% dto.", "5% off", "5% de réduction", "5% Rabatt", "−5%"),
    "6m": L("8% 할인", "8% off", "Giảm 8%", "8%オフ", "减 8%", "8% dto.", "8% off", "8% de réduction", "8% Rabatt", "−8%"),
    "12m": L("17% 할인", "17% off", "Giảm 17%", "17%オフ", "减 17%", "17% dto.", "17% off", "17% de réduction", "17% Rabatt", "−17%"),
  },
  erp_only: {
    "1m": E,
    "3m": L("6% 할인", "6% off", "Giảm 6%", "6%オフ", "减 6%", "6% dto.", "6% off", "6% de réduction", "6% Rabatt", "−6%"),
    "6m": L("8% 할인", "8% off", "Giảm 8%", "8%オフ", "减 8%", "8% dto.", "8% off", "8% de réduction", "8% Rabatt", "−8%"),
    "12m": L("17% 할인", "17% off", "Giảm 17%", "17%オフ", "减 17%", "17% dto.", "17% off", "17% de réduction", "17% Rabatt", "−17%"),
  },
  pro: {
    "1m": E,
    "3m": L("7% 할인", "7% off", "Giảm 7%", "7%オフ", "减 7%", "7% dto.", "7% off", "7% de réduction", "7% Rabatt", "−7%"),
    "6m": L("8% 할인", "8% off", "Giảm 8%", "8%オフ", "减 8%", "8% dto.", "8% off", "8% de réduction", "8% Rabatt", "−8%"),
    "12m": L(
      "23% 특가",
      "23% off",
      "Giảm 23%",
      "23%オフ",
      "减 23%",
      "23% dto.",
      "23% off",
      "23% de réduction",
      "23% Rabatt",
      "−23%",
    ),
  },
};

export const PLAN_TEXTS: Record<
  PlanId,
  { subName: LocalizedString; description: LocalizedString; features: LocalizedString[] }
> = {
  free: {
    subName: L(
      "화원 리본 출력 전용",
      "Focused on flower ribbon printing",
      "Tập trung in ruy băng hoa",
      "花屋リボン印刷に特化",
      "专注鲜花丝带打印",
      "Centrado en cintas florales",
      "Foco em fitas florais",
      "Axé sur rubans floraux",
      "Fokus: Blumenband-Druck",
      "Печать цветочных лент",
    ),
    description: L(
      "리본 프린터 출력을 위한 핵심 기능을 제공합니다. 안정적인 출력이 최우선인 사장님께 추천합니다.",
      "Core features for stable ribbon printing and basic order tracking.",
      "Tính năng cốt lõi cho in ruy băng ổn định và theo dõi đơn hàng cơ bản.",
      "リボンプリンタ向けの中核機能。安定した印刷を最優先するオーナー向け。",
      "为丝带打印机提供核心功能，适合将稳定输出放在首位的店主。",
      "Funciones esenciales para impresión estable de cintas y seguimiento básico de pedidos.",
      "Recursos essenciais para impressão estável de fitas e acompanhamento básico de pedidos.",
      "Fonctions clés pour une impression de rubans stable et un suivi simple des commandes.",
      "Kernfunktionen für stabilen Banddruck und einfache Auftragsübersicht.",
      "Базовые возможности для стабильной печати лент и учёта заказов.",
    ),
    features: [
      L(
        "무제한 리본 출력 (모든 규격 지원)",
        "Unlimited ribbon printing (all sizes)",
        "In ruy băng không giới hạn (mọi khổ)",
        "リボン印刷無制限（全サイズ対応）",
        "无限次丝带打印（全规格）",
        "Impresión ilimitada de cintas (todos los tamaños)",
        "Impressão ilimitada de fitas (todos os tamanhos)",
        "Impression illimitée de rubans (toutes tailles)",
        "Unbegrenzter Banddruck (alle Formate)",
        "Безлимитная печать лент (все форматы)",
      ),
      L(
        "전문 출력 로그 및 이력 상세 관리",
        "Detailed print logs and history",
        "Nhật ký in & lịch sử chi tiết",
        "詳細な印刷ログと履歴管理",
        "专业打印日志与历史记录",
        "Registros e historial de impresión detallados",
        "Logs e histórico de impressão detalhados",
        "Journaux et historique d’impression détaillés",
        "Ausführliche Druckprotokolle und Verlauf",
        "Подробные журналы и история печати",
      ),
      L(
        "고급 폰트 및 디자인 템플릿 라이브러리",
        "Premium font and template library",
        "Thư viện phông & mẫu cao cấp",
        "高品質フォントとテンプレートライブラリ",
        "高级字体与设计模板库",
        "Biblioteca premium de fuentes y plantillas",
        "Biblioteca premium de fontes e modelos",
        "Bibliothèque premium de polices et modèles",
        "Premium-Schriftarten und Vorlagenbibliothek",
        "Премиум-шрифты и библиотека шаблонов",
      ),
      L(
        "로컬 프린터 브릿지 무상 연동 서비스",
        "Local printer bridge integration",
        "Tích hợp bridge máy in cục bộ",
        "ローカルプリンターブリッジ連携（無償）",
        "本地打印机桥接免费接入",
        "Integración gratuita del puente de impresora local",
        "Integração gratuita da ponte de impressora local",
        "Intégration gratuite du pont d’impression locale",
        "Kostenlose lokale Druckerbridge-Integration",
        "Бесплатная интеграция локального моста принтера",
      ),
      L(
        "기본적인 주문 내역 수동 기록 및 관리",
        "Manual order record management",
        "Ghi nhận đơn hàng thủ công",
        "注文の手動記録と管理",
        "基础订单手动记录与管理",
        "Registro manual de pedidos",
        "Registro manual de pedidos",
        "Saisie manuelle des commandes",
        "Manuelle Auftragserfassung",
        "Ручной учёт заказов",
      ),
    ],
  },
  erp_only: {
    subName: L(
      "효율적인 화원 운영의 정석",
      "Efficient flower shop operations",
      "Vận hành tiệm hoa hiệu quả",
      "効率的な花屋運営の定番",
      "高效花店运营之选",
      "Operación eficiente de floristería",
      "Operação eficiente de floricultura",
      "Exploitation efficace d’un fleuriste",
      "Effizienter Blumenladen-Betrieb",
      "Эффективное ведение цветочного магазина",
    ),
    description: L(
      "정산 및 고객 관리를 위한 스마트 솔루션입니다. 데이터 기반의 성장을 원하는 사장님께 완벽합니다.",
      "Smart operations suite for settlement and customer growth.",
      "Bộ công cụ vận hành thông minh: quyết toán và phát triển khách hàng.",
      "精算と顧客管理のスマートスイート。データドリブンな成長を目指すオーナー向け。",
      "面向结算与客户增长的智能运营套件，适合数据驱动成长的店主。",
      "Suite inteligente para liquidaciones y crecimiento de clientes.",
      "Suíte inteligente para fechamentos e crescimento de clientes.",
      "Suite intelligente pour encaissement et croissance client.",
      "Smarte Suite für Abrechnung und Kundenwachstum.",
      "Умный набор для расчётов и роста клиентской базы.",
    ),
    features: [
      L(
        "고객 CRM + 포인트 마케팅 자동화",
        "Customer CRM + point marketing",
        "CRM khách hàng + marketing điểm thưởng",
        "顧客CRM＋ポイントマーケ自動化",
        "客户 CRM + 积分营销自动化",
        "CRM + marketing de puntos",
        "CRM + marketing de pontos",
        "CRM + marketing par points",
        "CRM + Punkte-Marketing",
        "CRM и маркетинг по баллам",
      ),
      L(
        "실시간 배송 배차 및 위치 추적 시스템",
        "Live delivery dispatch and tracking",
        "Điều phối giao hàng & theo dõi vị trí",
        "リアルタイム配車と位置追跡",
        "实时配送调度与位置跟踪",
        "Despacho y seguimiento de entregas en vivo",
        "Despacho e rastreamento de entregas ao vivo",
        "Dispatch et suivi de livraison en direct",
        "Live-Disposition und Sendungsverfolgung",
        "Диспетчеризация и трекинг доставки",
      ),
      L(
        "AI 영수증 OCR 정산 및 지출 내역 자동화",
        "AI receipt OCR for expense automation",
        "OCR hóa đơn AI cho chi phí tự động",
        "AI領収書OCRで経費自動計上",
        "AI 收据 OCR 自动记账与费用",
        "OCR de tickets con IA para gastos",
        "OCR de recibos com IA para despesas",
        "OCR de tickets IA pour les dépenses",
        "KI-Beleg-OCR für Ausgaben",
        "OCR чеков с ИИ для расходов",
      ),
      L(
        "매입 단가 추이분석 및 재고 관리",
        "Purchase price trend and inventory",
        "Xu hướng giá nhập & tồn kho",
        "仕入単価トレンドと在庫管理",
        "进价走势分析与库存管理",
        "Tendencia de precios de compra e inventario",
        "Tendência de preço de compra e estoque",
        "Tendance des prix d’achat et stocks",
        "Einkaufspreistrends und Lager",
        "Закупочные цены и склад",
      ),
      L(
        "자동 세무 설정 및 월간 손익 정산 보고서",
        "Auto tax setup and monthly P&L report",
        "Thiết lập thuế & báo cáo P&L hàng tháng",
        "税設定と月次損益レポート",
        "税务设置与月度损益报表",
        "Configuración fiscal e informe mensual PyG",
        "Configuração fiscal e relatório mensal DRE",
        "Paramétrage fiscal et rapport mensuel",
        "Steuereinstellungen und Monats-P&L",
        "Налоги и ежемесячный отчёт P&L",
      ),
    ],
  },
  pro: {
    subName: L(
      "완벽한 디지털 트랜스포메이션",
      "Complete digital transformation",
      "Chuyển đổi số toàn diện",
      "完全なデジタルトランスフォーメーション",
      "全面数字化转型",
      "Transformación digital completa",
      "Transformação digital completa",
      "Transformation numérique complète",
      "Vollständige digitale Transformation",
      "Полная цифровая трансформация",
    ),
    description: L(
      "프린터와 ERP, 마케팅 기능이 하나로 통합된 완전체입니다. 모든 것을 한 번에 해결하고 싶은 성공한 사장님의 선택.",
      "All-in-one printer, ERP, and marketing bundle for scaling teams.",
      "Gói máy in + ERP + marketing trong một, phù hợp mở rộng quy mô.",
      "プリンター・ERP・マーケを統合したオールインワン。スケールする店舗の選択。",
      "打印、ERP 与营销一体化，适合希望一站式扩展的成功店主。",
      "Todo en uno: impresora, ERP y marketing para equipos en crecimiento.",
      "Tudo-em-um: impressão, ERP e marketing para escalar.",
      "Tout-en-un : impression, ERP et marketing pour grandir.",
      "Alles-in-eins: Druck, ERP und Marketing zum Skalieren.",
      "Всё в одном: печать, ERP и маркетинг для роста.",
    ),
    features: [
      L(
        "PRINT + ERP 모든 기능 무제한 언리미티드",
        "Unlimited PRINT + ERP core features",
        "PRINT + ERP không giới hạn",
        "PRINT＋ERPの全機能が無制限",
        "PRINT + ERP 核心功能无限制",
        "PRINT + ERP ilimitado",
        "PRINT + ERP ilimitado",
        "PRINT + ERP illimité",
        "PRINT + ERP unbegrenzt",
        "Безлимит PRINT + ERP",
      ),
      L(
        "AI 사장님 비서 및 마케팅 원클릭 자동 포스팅",
        "AI assistant and one-click marketing posts",
        "Trợ lý AI & đăng bài marketing một chạm",
        "AIアシスタントとワンクリック投稿",
        "AI 店主助手与一键营销发帖",
        "Asistente IA y publicaciones con un clic",
        "Assistente de IA e posts com um clique",
        "Assistant IA et publications en un clic",
        "KI-Assistent und Ein-Klick-Posts",
        "ИИ-помощник и посты в один клик",
      ),
      L(
        "SNS(인스타/블로그) 실시간 연동 및 분석",
        "SNS integration and performance analysis",
        "Tích hợp mạng xã hội & phân tích",
        "SNS連携と分析（インスタ／ブログ）",
        "社交媒体（Ins/博客）联动与分析",
        "Integración SNS y analítica",
        "Integração SNS e análise",
        "Intégration RS et analyses",
        "SNS-Anbindung und Analysen",
        "SNS-интеграция и аналитика",
      ),
      L(
        "외부 쇼핑몰(파트너 갤러리) 주문 자동 스크래핑",
        "External marketplace order sync",
        "Đồng bộ đơn sàn thương mại bên ngoài",
        "外部モール注文の自動取り込み",
        "外部商城（合作画廊）订单自动同步",
        "Sincronización de pedidos de marketplaces",
        "Sincronização de pedidos de marketplaces",
        "Synchronisation des commandes marketplaces",
        "Marktplatz-Bestellungen synchronisieren",
        "Синхронизация заказов с витрин",
      ),
      L(
        "VIP 고객 전용 멤버십 전용관 개설 지원",
        "VIP membership storefront support",
        "Hỗ trợ cửa hàng thành viên VIP",
        "VIP向けメンバーシップ店舗の開設支援",
        "支持搭建 VIP 会员专属馆",
        "Soporte para tienda VIP de socios",
        "Suporte à vitrine de assinatura VIP",
        "Support vitrine adhérents VIP",
        "VIP-Mitgliedshop-Unterstützung",
        "Поддержка VIP-клуба для клиентов",
      ),
    ],
  },
};
