import { createClient } from "@supabase/supabase-js";
import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const TENANT_ID = "453db050-7181-4dd9-8f73-4162d89e928b"; // 릴리맥여의도점
const OUT_FILE = path.join(process.cwd(), "src", "lib", "tenant-master-seed", "seeds", "v2026-05-21-yeouido.generated.ts");

function tsEscape(s: unknown) {
  return String(s ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "")
    .replace(/\n/g, "\\n");
}

function emitCategoryData(data: any) {
  if (!data || !data.main || !data.mid) return `{\n  main: [],\n  mid: {},\n}`;
  const main = data.main.map((m: string) => `"${tsEscape(m)}"`).join(", ");
  const mids = data.main
    .map((k: string) => {
      const arr = data.mid[k] ?? [];
      const inner = arr.map((x: string) => `"${tsEscape(x)}"`).join(", ");
      return `    "${tsEscape(k)}": [${inner}],`;
    })
    .join("\n");
  return `{\n  main: [${main}],\n  mid: {\n${mids}\n  },\n}`;
}

async function run() {
  console.log("Fetching data for tenant:", TENANT_ID);

  // 1. Fetch system_settings (categories + delivery)
  const { data: settings } = await supabase
    .from("system_settings")
    .select("id, data")
    .eq("tenant_id", TENANT_ID)
    .in("id", ["product_categories", "material_categories", "expense_categories", `settings_${TENANT_ID}`, "general"]);

  const prodCat = settings?.find((s) => s.id === "product_categories")?.data;
  const matCat = settings?.find((s) => s.id === "material_categories")?.data;
  const expCat = settings?.find((s) => s.id === "expense_categories")?.data;

  // 2. Fetch products
  const { data: products } = await supabase
    .from("products")
    .select("name, main_category, mid_category, code, price, stock, status")
    .eq("tenant_id", TENANT_ID)
    .order("created_at", { ascending: true });

  // 3. Fetch materials
  const { data: materials } = await supabase
    .from("materials")
    .select("name, main_category, mid_category, unit, spec")
    .eq("tenant_id", TENANT_ID)
    .order("created_at", { ascending: true });

  // 4. Fetch suppliers
  const { data: suppliers } = await supabase
    .from("suppliers")
    .select("name, supplier_type, memo")
    .eq("tenant_id", TENANT_ID)
    .order("created_at", { ascending: true });

  const productsTs = (products ?? [])
    .map(
      (p) =>
        `    { name: "${tsEscape(p.name)}", main_category: "${tsEscape(p.main_category)}", mid_category: "${tsEscape(p.mid_category)}", code: "${tsEscape(p.code)}", price: ${p.price || 0}, stock: ${p.stock || 0}, status: "${tsEscape(p.status)}" },`
    )
    .join("\n");

  const materialsTs = (materials ?? [])
    .map(
      (m) =>
        `    { name: "${tsEscape(m.name)}", main_category: "${tsEscape(m.main_category)}", mid_category: "${tsEscape(m.mid_category)}", unit: "${tsEscape(m.unit)}", spec: "${tsEscape(m.spec)}" },`
    )
    .join("\n");

  const suppliersTs = (suppliers ?? [])
    .map((s) => {
      const memo = s.memo ? `, memo: "${tsEscape(s.memo)}"` : "";
      const st = s.supplier_type ? `, supplier_type: "${tsEscape(s.supplier_type)}"` : "";
      return `    { name: "${tsEscape(s.name)}"${st}${memo} },`;
    })
    .join("\n");

  const header = `/**
 * AUTO-GENERATED by scripts/extract-db-seed.ts
 * Source: Database (Tenant: 릴리맥여의도점)
 */
import { DEFAULT_EXPENSE_CATEGORIES } from "@/lib/category-defaults";
import type { TenantMasterSeed } from "../types";
import { TENANT_MASTER_SEED_DELIVERY_GWANGHWAMUN } from "./delivery-gwanghwamun";

export const TENANT_MASTER_SEED_V2026_05_21_YEOUIDO: TenantMasterSeed = {
  version: "v2026-05-21-yeouido",
  label: "릴리맥여의도점 시트 스냅샷 (상품·자재·거래처)",
  productCategories: ${prodCat ? emitCategoryData(prodCat) : "{\n  main: [],\n  mid: {}\n}"},
  materialCategories: ${matCat ? emitCategoryData(matCat) : "{\n  main: [],\n  mid: {}\n}"},
  expenseCategories: ${expCat ? emitCategoryData(expCat) : "DEFAULT_EXPENSE_CATEGORIES"},
  suppliers: [
${suppliersTs}
  ],
  products: [
${productsTs}
  ],
  materials: [
${materialsTs}
  ],
  delivery: { ...TENANT_MASTER_SEED_DELIVERY_GWANGHWAMUN },
};
`;

  fs.writeFileSync(OUT_FILE, header, "utf8");
  console.log("Wrote", OUT_FILE);
  console.log("Stats:", {
    products: products?.length,
    materials: materials?.length,
    suppliers: suppliers?.length,
  });
}

run();
