ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS terms_agreed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS privacy_agreed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS age_agreed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS marketing_agreed_at TIMESTAMPTZ;
